### ISSUE TITLE
Running 'snapshot reset_simulators' in Xcode 9 GM deletes all sims but does not reinstall them

### ISSUE THREAD

**Issue by paul-bonneville** [fastlane/fastlane#10354]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running 'snapshot reset_simulators' in Xcode 9 GM deletes all sims but does not reinstall them. I am left with no simulators at all. In the "Devices & Simulators", iOS 11 simulators aren't even an option for download. I could go through and manually recreate all the simulators, but there has to be a better way. I re-extracted the Xcode 9 GM build from the tip file but it seems the flag for "installing additional components" is tripped so it does not download any simulators. Any thoughts on how to reinstall my simulators, including for iOS 11?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

See environment

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.5 (Apple Git-94)           |
| Installation Source         | ~/.rbenv/versions/2.2.4/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.4/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.12.1       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
</details>

*generated on:* **2017-09-18**
</details>

**Comment by ryanoconnor7** [comment]
I too am having this issue, except in my case, I see iPhone2017-A/B/C in place of 8/8 Plus/X when I try to re-add the simulators. Additionally, iOS 11 does not appear in components download section.

**Comment by confucious** [comment]
I believe this is fixed in 2.57.0

**Comment by weien** [comment]
@confucious thanks for the tip!

**Comment by KrauseFx** [comment]
Is this fixed now with the most recent release? Any action required from our side?

**Comment by weien** [comment]
@KrauseFx updating fastlane and then running `reset_simulators` a second time produced the expected simulators! I don't think any other action is required at least for the original poster's case. Thank you for checking in!

**Comment by moonorblue** [comment]
I too have the issue when `reset_simulators` leads to iPhone2017-A/B/C in place of 8/8 Plus/X
![2017-09-27 5 24 49](https://user-images.githubusercontent.com/1680971/30905925-df847b44-a33b-11e7-9064-b5f8482151f6.png)
![2017-09-27 5 25 01](https://user-images.githubusercontent.com/1680971/30905924-df825eea-a33b-11e7-94bc-0b4be41a0181.png)

**Comment by KimAM** [comment]
I'm running `fastlane snapshot reset_simulators` with Fastlane 2.59.0 and I still get the same iPhone2017-a/b/c simulators.. Anything I need to clean up?

**Comment by KrauseFx** [comment]
Alright, I see the the ABC issue, however this is not related with the original issue at all, right? 

Also, I don't know why the ABC is generated, I can reproduce this locally, but it looks like those are different simulators, so snapshot will generate them. What's the expected behavior? Let's move this to a new issue, I'll lock this one for now
