### ISSUE TITLE
IAPs pricing not working after Introductory Pricing

### ISSUE THREAD

**Issue by alaincaltieri** [fastlane/fastlane#11189]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Starting since yesterday, on iTunes connect the new `Introductory Pricing` feature has been deployed. This refactors the management of both Pricing and trial period for Auto renewable subscriptions and causes the current version of Spaceship to fail in both retrieving and saving pricing information for auto renewable subscriptions.

Let me know if you'd like some help on this, I'd be happy to contribute.

**Comment by taquitos** [comment]
@alaincaltieri that would be amazing! We have some information on how we usually go about fixing issues like this: https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md
I'm not sure when we'll be able to fix this issue in fastlane, but if you feel up to the challenge of updating the api, we can provide some guidance 👍

**Comment by alaincaltieri** [comment]
Awesome! Thanks for the doc. Will keep you posted with my progress

**Comment by ahmgeek** [comment]
is there any progress on this guys?

**Comment by alaincaltieri** [comment]
Had no chance to have a look at it yet, sorry :(

**Comment by ahmgeek** [comment]
I already fixed id 🤗  will send a PR tomorrow.

**Comment by untitaker** [comment]
@aht's PR partially fixes this by using the new API endpoint where the pricing information moved to. However, we've noticed another change wrt how trials are represented in ITC.

Spaceship's IAPDetails currently maps the `freeTrialDurationType` key to `subscription_free_trial`, but since everything is an initial offer now, this key is no longer used and always set to `null`.

I don't see an easy way to map the new model to the old model and therefore suggest to remove this attribute for now and work on a proper implementation of introductory pricing in a separate issue.

**Comment by byohay** [comment]
I'm working on a fix that will send the request to the new API, both when getting and updating pricing. Will open the PR soon :)

**Comment by luongm** [comment]
The PR made by @byohay should have fixed this issue. Although free trial is still broken because it was migrated after Introductory Pricing too, but that can be a separate issue
