### ISSUE TITLE
Server error got 500, but IPA file still success in TestFlight

### ISSUE THREAD

**Issue by lancedolan** [fastlane/fastlane#13452]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I run my lane (`fastlane beta`) which builds and pushes up to TestFlight.  Used to work fine, now ends with:
```
[11:23:22]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
...
(Shows some issues which are closed and appear different/unrelated)
...
[!] The request could not be completed because:
	Server error got 500
```

Interestingly, the app is still pushed successfully to TestFlight and can be run as usual. I can essentially ignore this error and go about business as usual.

My Fastfile
```
default_platform(:ios)

platform :ios do

  desc "Increment Build Number"
  lane :increment do
    increment_build_number(xcodeproj: "CmsMmobileAapp.xcodeproj")
  end

  desc "Remove NSExceptionDomains"
  lane :NSExceptionDomains do
  update_info_plist(
    plist_path: "CmsMmobileAapp/Info.plist",
    block: proc do |plist|
      plist[:NSAppTransportSecurity] = {}
    end
  )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    NSExceptionDomains()
    build_app(scheme: "CmsMmobileAapp", configuration: "Release")
    upload_to_testflight
  end

end
```

##### Complete output when running fastlane, including the stack trace and command used

With `--capture_output` it ends with this:
```
INFO [2018-09-27 11:49:37.13]: Successfully finished processing the build 1.2 - 46
INFO [2018-09-27 11:49:37.13]: Distributing new build to testers: 1.2 - 46
WARN [2018-09-27 11:49:37.63]: Lane Context:
INFO [2018-09-27 11:49:37.63]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :IPA_OUTPUT_PATH=>"/Users/lancedolan/sourcecode/CmsMmobileAapp/ios/CmsMmobileAapp.ipa", :DSYM_OUTPUT_PATH=>"/Users/lancedolan/sourcecode/CmsMmobileAapp/ios/CmsMmobileAapp.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/lancedolan/Library/Developer/Xcode/Archives/2018-09-27/CmsMmobileAapp 2018-09-27 11.43.36.xcarchive"}
ERROR [2018-09-27 11:49:37.63]: Server error got 500
INFO [2018-09-27 11:49:37.63]: Successfully generated documentation at path '/Users/lancedolan/sourcecode/CmsMmobileAapp/ios/fastlane/README.md'
ERROR [2018-09-27 11:49:37.64]: fastlane finished with errors
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.16.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.3 (17D47)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Increment Build Number"
  lane :increment do
    increment_build_number(xcodeproj: "CmsMmobileAapp.xcodeproj")
  end

  desc "Remove NSExceptionDomains"
  lane :NSExceptionDomains do
  update_info_plist(
    plist_path: "CmsMmobileAapp/Info.plist",
    block: proc do |plist|
      plist[:NSAppTransportSecurity] = {}
    end
  )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    NSExceptionDomains()
    build_app(scheme: "CmsMmobileAapp", configuration: "Release")
    upload_to_testflight
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("CHANGED.CHANGED.CHANGED") # The bundle identifier of your app
apple_id("CHANGED@CHANGED.com") # Your Apple email address

itc_team_id("CHANGED") # iTunes Connect Team ID
team_id("CHANGED") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.4.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-09-27**
</details>

**Comment by lancedolan** [comment]
I update regularly and this issue started after an update. Of course I also made changes of my own betweens builds, but appears more like to have ben the fastlane update and not my changes that caused this.

**Comment by TTSMike** [comment]
I had the same error yesterday as well (about 3 hours after was posted). It was our first Testflight deployment using Fastlane, so I wasn't sure what to expect. Our game did eventually show up in the iTunes portal, and everything did eventually work. Our binary is quite large, currently a 300 MB IPA, so I'm not sure if that's related.

**Comment by marekpridal** [comment]
Same error here. It is probable realted with setting changelog see #13432

**Comment by marekpridal** [comment]
I fixed it with setting `<key>ITSAppUsesNonExemptEncryption</key><false/>` in my info p list. Probably problem with (not) providing export compliance. Fastlane doesn't provide better solution because of missing support of providing export compliance.

**Comment by suoxj** [comment]
I have the same error right now, and I didn't set any changelog, does anybody have some solutions? I I use fastlane 2.105.2, and the pilot arguments are :
pilot(
         ipa: "V4.8.3_2018092001.ipa",
         wait_for_uploaded_build: true
         #submit_for_review: true,
        )

**Comment by jdeanwaite** [comment]
@marekpridal Thank you, solved for me.

**Comment by philicious** [comment]
We are seeing the same problem for like 1-2 weeks. First thought it was a missing fastlane update but after the update it still happened.

**Comment by jdeanwaite** [comment]
@philicious did you try adding
```
<key>ITSAppUsesNonExemptEncryption</key><false/>
```
to your info.plist?

**Comment by ahilles107** [comment]
@jdeanwaite i have it in plist and problem stil exists.

**Comment by suoxj** [comment]
@jdeanwaite 
The error is still after I added the 

 App Uses Non-Exempt Encryption   Boolean  NO

 to my  info.plist


I still got the error message:

[!] The request could not be completed because:
	Server error got 500

**Comment by lancedolan** [comment]
Answering the encryption question with the `ITSAppUsesNonExemptEncryption` property does seem to solve the 500. However, it seems "normal" for a software like `fastlane` to handle this error more gracefully. 

More than anything, it's surprising that apple servers are even responding 500 in this circumstance; Before we could simply log in to iTunes Connect and answer the exemption question separately, and furthermore 500 isn't an appropriate response status for successful transaction with the server in which the server expected some extra information.... Maybe a 400 at worst would be appropriate 👎

**Comment by philicious** [comment]
I can now also report the 
```<key>ITSAppUsesNonExemptEncryption</key><false/>```

fixes the problem for us

**Comment by geraldeersteling** [comment]
Like @lancedolan; I tried doing the same (adding the `ITSAppUsesNonExemptEncryption` key), but I still encounter the same 500 when fastlane finishes.

Are there any other solutions tried? This is a quite annoying error since all my pipelines now fail as well 😕

**Comment by pparmaei** [comment]
I am still seeing the same error 500 error too. 

Additionally, I have tried to investigate further. When I look at the build in Spaceship, I see:

```
The value of build processed?       -> true
The value of build active?          -> false
The value of build ready_to_submit? -> false
The value of build ready_to_test?   -> false
The value of build approved?        -> false
The value of build processing?      -> false
The value of build approved?        -> false
The internal state is               -> testflight.build.state.export.compliance.missing
The external state is               -> testflight.build.state.export.compliance.missing
```

However, on App Store Connect I see the status is still **Processing** under **App Store Connect Users**

![image](https://user-images.githubusercontent.com/23205547/49185069-c765cb00-f315-11e8-81a8-9c43130c59c1.png)

It looks like even though the value of build.processed? is set to true, the build is actually not yet processed on App Store Connect.

**Comment by anushkmittal** [comment]
bump same

**Comment by Cnordbo** [comment]
I believe this is related to the compliance agreement you have to sign everytime you upload a new app to TestFlight (might be the same for appstore, but havent tried that yet). 

By adding this key-value that is mentioned earlier in this issue, `<key>ITSAppUsesNonExemptEncryption</key><false/>` into `Info.plist`, solved the issue for me. 500 error is given as Fastlane tries to publish the app directly without signing the compliance - Probably just a missing step in their process, if the step can be automated at all.

**Comment by lucasmpaim** [comment]
+1

**Comment by lucasmpaim** [comment]
I'm not sure, but when added the following snippet this errors stop occurs, and the upload started running without problems

```
  begin
    upload_to_testflight
  rescue
    puts "Error on TestFlight"
  end
```

**Comment by trevoriancox** [comment]
I just got this error with fastlane 2.111. The went to testflight regardless, and I was able to publish it normally. Other apps based on the same source code (and same ITSAppUsesNonExemptEncryption etc) did not get the error.

**Comment by wdcurry** [comment]
Solution of injecting 
`<key>ITSAppUsesNonExemptEncryption</key><false/>
`
