### ISSUE TITLE
Successful lane run returns non-zero exit code when using resign.sh

### ISSUE THREAD

**Issue by goraths** [fastlane/fastlane#13517]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running our release lane, Fastlane is returning a nonzero exit code even though the lane seemingly succeeds. The re-sign succeeds because we can upload to the App Store as part of our deployment process. The upload succeeds because we see the build in the App Store immediately after running this deployment. The best clue I have to what is failing is this:

`rm: _floatsignTemp/old-embedded-profile.plist: No such file or directory`

This line comes from `fastlane/sigh/lib/assets/resign.sh`. resign.sh tries to remove the old embedded plist near the end of the script, line 844: 

`rm -r "$TEMP_DIR/old-embedded-profile.plist"`

This should be `rm -f` like the other items that get deleted, then the error message that occurs when the file doesn't exist would be suppressed.  Also -r is recursive and this command just removes a single file. This is a bug regardless of whether that actually fixes my issue. Another solution might be to understand why the script tries to remove a file that no longer exists or was never created. I can make a quick fix and PR for this if it's just the simple one character change.

It's also possible something under the hood is going on during the upload process that is causing a failure even though the upload succeeds. This seems less likely since running the build in a non-CI environment works without issues.

Thanks for a great tool and for looking into this!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
-----------------------------
--- Step: import_from_git ---
-----------------------------
Cloning remote git repo...
$ GIT_TERMINAL_PROMPT=0 git clone 'ssh://build-fastlane.git' '/var/folders/7m/njbmxl1n7fs8yrnfnz_ds2c0ykp5fl/T/fl_clone20181010-72810-7in5mm/build-fastlane.git' --depth 1 -n 
▸ Cloning into '/var/folders/7m/njbmxl1n7fs8yrnfnz_ds2c0ykp5fl/T/fl_clone20181010-72810-7in5mm/build-fastlane.git'...
$ cd '/var/folders/7m/njbmxl1n7fs8yrnfnz_ds2c0ykp5fl/T/fl_clone20181010-72810-7in5mm/build-fastlane.git' && git checkout HEAD 'fastlane/Fastfile'
$ cd '/var/folders/7m/njbmxl1n7fs8yrnfnz_ds2c0ykp5fl/T/fl_clone20181010-72810-7in5mm/build-fastlane.git' && git checkout HEAD 'fastlane/actions'
------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'ios release' 🚀
-----------------------------
--- Step: unlock_keychain ---
-----------------------------
Unlocking keychain at path: appstore.keychain
--------------------------------------
--- Step: get_provisioning_profile ---
--------------------------------------

+-------------------------------------+-----------------------------+
|                     Summary for sigh 2.105.2                      |
+-------------------------------------+-----------------------------+
| skip_install                        | true                        |
| adhoc                               | false                       |
| development                         | false                       |
| force                               | false                       |
| app_identifier                      | game                        |
| username                            | name                        |
| team_id                             | id                          |
| ignore_profiles_with_different_name | false                       |
| skip_fetch_profiles                 | false                       |
| skip_certificate_verification       | false                       |
| platform                            | ios                         |
| readonly                            | false                       |
+-------------------------------------+-----------------------------+

Starting login with user 'user'
Successfully logged in
Fetching profiles...
Verifying certificates...
Found 1 matching profile(s)
Downloading provisioning profile...
Successfully downloaded provisioning profile...
AppStore_game.mobileprovision
Setting Provisioning Profile type to 'app-store'
--------------------
--- Step: resign ---
--------------------
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.105.2/sigh/lib/assets/resign.sh game.ipa 34160347E30C8A549A36611137421BC9FC7EDBA4 -p /Users/bamboo/bamboo-agent-home/xml-data/pStore_game.mobileprovision         --keychain-path /Users/bamboo/Library/Keychains/appstore.keychain game.ipa
_floatsignTemp/Payload/hoops.app: replacing existing signature
rm: _floatsignTemp/old-embedded-profile.plist: No such file or directory

Successfully signed game.ipa!
Successfully re-signed .ipa 🔏.
---------------------------------
--- Step: upload_to_app_store ---
---------------------------------
Login to App Store Connect (game)
Login successful

+--------------------------------------+-----------------------------+
|                      deliver 2.105.2 Summary                       |
+--------------------------------------+-----------------------------+
| ipa                                  | game.ipa                    |
| run_precheck_before_submit           | false                       |
| skip_metadata                        | true                        |
| skip_screenshots                     | true                        |
| screenshots_path                     | ./fastlane/screenshots      |
| metadata_path                        | ./fastlane/metadata         |
| app_version                          | 0.0.1                       |
| username                             | user                        |
| app_identifier                       | game                        |
| platform                             | ios                         |
| edit_live                            | false                       |
| use_live_version                     | false                       |
| skip_binary_upload                   | false                       |
| skip_app_version_update              | false                       |
| force                                | false                       |
| overwrite_screenshots                | false                       |
| submit_for_review                    | false                       |
| reject_if_possible                   | false                       |
| automatic_release                    | false                       |
| phased_release                       | false                       |
| team_id                              | id                          |
| dev_portal_team_id                   | id                          |
| precheck_default_rule_level          | warn                        |
| ignore_language_directory_validatio  | false                       |
| n                                    |                             |
| precheck_include_in_app_purchases    | true                        |
+--------------------------------------+-----------------------------+

Making sure the latest version on App Store Connect matches '0.0.1' from the ipa file...
Successfully set the version to '0.0.1'
Uploading binary to App Store Connect
Going to upload updated app to App Store Connect
This might take a few minutes. Please don't interrupt the script.
Failing task since return code of [/var/folders/7m/njbmxl1n7fs8yrnfnz_ds2c0ykp5fl/T/epb6468691893660389944.sh ios release keychain_password:********] was -1 while expected 0</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.11.4                                       |
| Ruby                        | 2.5.1                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.17.0                            |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.11.4 (15E65)                      |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib              |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode_8.app/Contents/Developer/ |
| Xcode Version               | 8.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform(:ios)

platform :ios do
    desc "Submit an IPA to the App Store"
    lane :release do |options|
        default_keychain_path = File.expand_path("~/Library/Keychains/appstore.keychain")
        default_signing_identity = "iPhone Distribution"
        default_bundle_path = find_bundle(:ipa)

        unlock_keychain(
            path: (options[:keychain_path] or default_keychain_path),
            password: options[:keychain_password]
        )

        get_provisioning_profile(
            skip_install: true
        )

        resign(
            ipa: (options[:bundle_path] or default_bundle_path),
            signing_identity:  (options[:signing_identity] or default_signing_identity),
            keychain_path: (options[:keychain_path] or default_keychain_path)
        )

        upload_to_app_store(
            ipa: (options[:bundle_path] or default_bundle_path),
            run_precheck_before_submit: false,
            skip_metadata: true,
            skip_screenshots: true
        )

        clean_build_artifacts()
    end
end

error do |lane, exception|
    if lane_context[SharedValues::PLATFORM_NAME] == "ios"
        clean_build_artifacts()
    end
end

def find_bundle(bundle_type)
    bundle_glob = { :ipa => "**/*.ipa", :apk => "**/*.apk" }

    ipas = []

    Dir.chdir("..") do
        ipas = Dir[bundle_glob[bundle_type]]
    end

    if ipas.length > 1
        UI.user_error!("More than one IPA or APK found to upload. Please specify which you want to upload using the bundle_path parameter.")
    end

    if ipas.length == 0
        UI.user_error!("No IPAs or APKs found in the current directory and subdirectories. Please specify a location using the bundle_path parameter.")
    end

    return ipas[0]
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
##### iOS #####

app_identifier("com.fakegame") # The bundle identifier of your app
apple_id("apple@apple.apple") # Your Apple email address

itc_team_id("itc_team id") # iTunes Connect Team ID
team_id("team_id") # Developer Portal Team ID

##### Android #####

package_name("com.fakegame")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.106.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.5.0        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| msgpack                   | 1.2.4        |
| bootsnap                  | 1.3.2        |
| openssl                   | 2.1.0        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
</details>

*generated on:* **2018-10-10**
</details></pre>
</details>

**Comment by getaaron** [comment]
I merged that fix, but I agree that this wouldn't cause an erroneous nonzero exit code

**Comment by goraths** [comment]
Okay, thanks for the fix. I'll test it when the new version comes out. Sounds like it won't address this. I can do more experimentation to see what the actual cause might be.

**Comment by janpio** [comment]
@goraths Did you have time to review the new fastlane releases?

**Comment by goraths** [comment]
I did. I'm not on the latest latest release, but I ran a deployment on 2.106.1, which I believe has the change to fix the rm -r line. It didn't fix the non-zero exit code I was seeing. I'll have to come up with a different test case to repro this to see if I can get better debug output because what I'm seeing is not enough to tell what's going wrong.
