### ISSUE TITLE
Fastlane Error

### ISSUE THREAD

**Issue by cormackerinsunily** [fastlane/fastlane#15671]
MAC OS recently upgraded and fastlane now throwing errors

 The request could not be completed because:
	Could not receive latest API key from App Store Connect, this might be a server issue.

![image](https://user-images.githubusercontent.com/48317654/69045455-c6c6b880-09ee-11ea-9770-e8e5142a7608.png)

Have attempted all fixes from GH but still receive the above

**Comment by cormackerinsunily** [comment]
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    
    desc "Configure app"
    lane :dev_portal_config do
        cert(
            output_path: 'fastlane/certificates'
        )
        produce(
            app_name: ENV['APP_NAME'],
            language: 'English',
            app_version: ENV['APP_VERSION'],
            sku: ENV['APP_SKU'],
            skip_itc: 'true',
            enable_services: {
                push_notification: "on"
            }
        )

        gen_apn = prompt(text: "Do you want to generate a Push Notification certificate for >>> #{ENV['APP_NAME']} <<< [LEGACY]", boolean: true)
        if gen_apn
            puts "Creating a push certificate for #{ENV['APP_NAME']}"
            pem(
              p12_password: '****',
              output_path: 'fastlane/push-certificates'
            )
        else
            puts "Don't forget to create the Token to use with the Azure Notification Hub"
        end

        sigh(
          output_path: 'fastlane/profiles'
        )
    end
  
    # Not currently in use and have not been maintained
  
    # # Lane to renew push notification certificates
    # desc "Renew push notification certificate (if less than 30 days)"
    # lane :renew_push do
    #     renew = prompt(text: "Renew push notification certificate (if < 30 days remain) for >>> #{ENV['APP_NAME']} <<<", boolean: true)
    #     if renew
    #         puts "Renewing for #{ENV['APP_NAME']}"
    #         pem
    #     else
    #         puts "You chose not to renew"
    #     end
    # end
    #
    # # Lane to force renew push notification certificates
    # # This will create a new one on developer.apple.com and the old one will still exist until you go and revoke it
    # desc "Renew push notification certificate (force it!)"
    # lane :force_renew_push do
    #     renew = prompt(text: "Forcefully renew push notification certificate for >>> #{ENV['APP_NAME']} <<<", boolean: true)
    #     if renew
    #         double_check = prompt(text: "Are you sure you want to renew for >>> #{ENV['APP_NAME']} <<<", boolean: true)
    #         if double_check
    #             puts "Renewing for #{ENV['APP_NAME']}"
    #             get_push_certificate(force: true)
    #         else
    #             puts "You chose not to renew"
    #         end
    #     else
    #         puts "You chose not to renew"
    #     end
    # end
    #
    # error do |lane, exception|
    #
    # end
    
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"]
apple_id("****") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.119.0 | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

**Comment by emkou** [comment]
Facing the same issue with fastlane, can it be Apple changed API?

**Comment by cormackerinsunily** [comment]
I was not aware of this. Nothing on the Apple portal. Can you suggest a work around

**Comment by emkou** [comment]
Update to latest fastlane, it seems that the issue is fixed there.

**Comment by hamzahayat** [comment]
I have the `update_fastlane` command at the very top of my Fastfile, which should theoretically update fastlane every-time. 

Going over my logs, I can see that fastlane does get successfully updated. However, I still see this error.

**Comment by amaurydavid** [comment]
Same issue here on Fastlane 2.119 and xcode 10.2.1:
```
Login to App Store Connect (<login>)
Available session is not valid any more. Continuing with normal login.
Failed to open TCP connection to olympus.itunes.apple.com:443 (getaddrinfo: nodename nor servname provided, or not known)
 Could not receive latest API key from App Store Connect, this might be a server issue.
```
As suggested by @emkou , updating to the lastest Fastlane fixed it.

**Comment by cormackerinsunily** [comment]
Thanks everyone will complete the upgrade

**Comment by YakirSolomon** [comment]
Still happens here, although I've upgraded Fastlane :(

**Comment by hamzahayat** [comment]
I ended up having to update fastlane using **Bundler**.  
If you're working on a react-native project, navigate to the `ios` directory and then run the command below.  
```
bundle update fastlane
```
NOTE: For anyone that is **using CircleCI for building their project**, you may also need to update your ruby version within your `config.yml` file. You can find the documentation on how to do that over [here](https://circleci.com/docs/2.0/testing-ios/#custom-ruby-versions).

**Comment by chrisoname** [comment]
What's the status for this? Does anyone know the actual issue? Should we wait for a fix on Fastlane's side or is it Apple's fault?

**Comment by mkabatek** [comment]
Same problem.

**Comment by YakirSolomon** [comment]
Does anyone know the minimum version that this issue is being addresses in? 
Temporarily can't upgrade to latest Fastlane :/

**Comment by entotsu** [comment]
Same problem.

**Comment by Vyazovoy** [comment]
@YakirSolomon , the minimum fastlane version that supports new AppStoreConnect API is `2.120.0` because #14509.

**Comment by entotsu** [comment]
It was solved by updating fastlane.

**Comment by cormackerinsunily** [comment]
Opted to roll back the OS if you have time machine

**Comment by Odelia0808** [comment]
thanks.update from 2.113 to 2.140 solved my problem.

**Comment by Odelia0808** [comment]
> I have the `update_fastlane` command at the very top of my Fastfile, which should theoretically update fastlane every-time.
> 
> Going over my logs, I can see that fastlane does get successfully updated. However, I still see this error.

did you change the fastlane version declared in you gemfile(in the root directory)?and then run“ "bundle update fastlane" or "fastlane update_fastlane --verbose" to update fastlane。 you may see has update successfully.

**Comment by qadirsuh** [comment]
Same error.

`[03:55:25]: Could not receive latest API key from App Store Connect, this might be a server issue.

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | setup_circle_ci        | 0           |
| 3    | increment_build_number | 2           |
| 💥   | match                  | 25          |
+------+------------------------+-------------+

[03:55:25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane spaceauth
    https://github.com/fastlane/fastlane/issues/15821 [open] 2 💬
    a week ago

➡️  Fastlane Error
    https://github.com/fastlane/fastlane/issues/15671 [closed] 18 💬
    3 weeks ago

➡️  Could not receive latest API key from App Store Connect, this might be a server issue.
    https://github.com/fastlane/fastlane/issues/14750 [closed] 10 💬
    16 Aug 2019

and 4 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Could%20not%20receive%20latest%20API%20key%20from%20App%20Store%20Connect%2C%20this%20might%20be%20a%20server%20issue.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	Could not receive latest API key from App Store Connect, this might be a server issue.`

**Comment by cormackerinsunily** [comment]
> Same error. I am using circleCI.
> 
> ```
> [03:55:25]: Could not receive latest API key from App Store Connect, this might be a server issue.
> +------+------------------------+-------------+
> |              fastlane summary               |
> +------+------------------------+-------------+
> | Step | Action                 | Time (in s) |
> +------+------------------------+-------------+
> | 1    | default_platform       | 0           |
> | 2    | setup_circle_ci        | 0           |
> | 3    | increment_build_number | 2           |
> | 💥   | match                  | 25          |
> +------+------------------------+-------------+
> 
> [03:55:25]: fastlane finished with errors
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  fastlane spaceauth
>     https://github.com/fastlane/fastlane/issues/15821 [open] 2 💬
>     a week ago
> 
> ➡️  Fastlane Error
>     https://github.com/fastlane/fastlane/issues/15671 [closed] 18 💬
>     3 weeks ago
> 
> ➡️  Could not receive latest API key from App Store Connect, this might be a server issue.
>     https://github.com/fastlane/fastlane/issues/14750 [closed] 10 💬
>     16 Aug 2019
> 
> and 4 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because%3A%0A%09Could%20not%20receive%20latest%20API%20key%20from%20App%20Store%20Connect%2C%20this%20might%20be%20a%20server%20issue.&type=Issues&utf8=✓
> 
> 🔗  You can ⌘ + double-click on links to open them directly in your browser.
> 
> [!] The request could not be completed because:
> 	Could not receive latest API key from App Store Connect, this might be a server issue.
> ```

We rolled back the OS to fix the issue. If you need a quick fix go with the roll back

**Comment by wzbozon** [comment]
If you use `Gemfile` and `bundler`: 

```
$ sudo chmod 777 Gemfile.lock
$ bundle update fastlane
```
