### ISSUE TITLE
fastlane unable to load available devices

### ISSUE THREAD

**Issue by MoteebN** [fastlane/fastlane#15874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Upon trying to run "fastlane screengrab" there seems to be an error trying to 'load_all_devices", this results in a crash immediately. I'm unsure if this is a Catalina bug, so I had updated ruby, bundle, and fastlane to try and fix it, but to no avail. This occurs on Android, (I also boiled the error down to a very basic command (screengrab) to try and help others debug this error).

##### Command executed

fastlane screengrab
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [Traceback (most recent call last):
	16: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `<main>'
	13: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `load'
	12: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	 9: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	 8: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 2: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 1: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
/Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/adb_helper.rb:55:in `load_all_devices': undefined method `shellescape' for nil:NilClass (NoMethodError)
	16: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `<main>'
	15: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in `eval'
	14: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `<main>'
	13: from /Users/bryant/.rvm/gems/ruby-2.6.1/bin/fastlane:23:in `load'
	12: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	 9: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	 8: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 2: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 1: from /Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
/Users/bryant/.rvm/gems/ruby-2.6.1/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/adb_helper.rb:55:in `load_all_devices': [!] undefined method `shellescape' for nil:NilClass (NoMethodError)] </pre>
</details>

### Environment

<details>
  <pre> [<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.2                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.22.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.1/bin/fastlane         |
| Host                        | Mac OS X 10.15.2 (19C57)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/bryant/Desktop/fastlane/api-5954702082857151067-233022-88f3be17ac72.json") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.homecu.demo") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 2.1.2        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.71.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-01-10**
</details>] </pre>
</details>

**Comment by hauthorn** [comment]
I have similar/same error.
Tried on fastlane 2.139.0 and 2.140.0.

I'm running on linux (ubuntu 19.10), Android build chain is newest (29.0.2 or whatever).

**Comment by hex22a** [comment]
Same issue 😅Any ideas what it could be? I have an emulator up and running my app.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.2                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.2 (19C57)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
   # iOS Lanes
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(
      task: 'assemble',
      build_type: 'Release',
      project_dir: 'android/'
      )
  end

  desc 'Ship to Playstore Beta.'
    lane :beta do
      build
      supply(track: 'beta', track_promote_to: 'beta')
    end

    desc "Build debug and test APK for screenshots"
      lane :build_for_screengrab do
        gradle(
          task: 'clean',
          project_dir: 'android/'
        )
        build_android_app(
          task: 'assemble',
          build_type: 'Debug',
          project_dir: 'android/'
        )
        build_android_app(
          task: 'assemble',
          build_type: 'AndroidTest',
          project_dir: 'android/'
        )
      end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("/Users/hex22a/Dropbox/Job/Crftd/saitama-service-fastlane.json")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>


*generated on:* **2020-01-16**
</details>

Traceback (most recent call last):
	14: from /Users/hex22a/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	13: from /Users/hex22a/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	12: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	 9: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	 8: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 2: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 1: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
/Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/adb_helper.rb:55:in `load_all_devices': undefined method `shellescape' for nil:NilClass (NoMethodError)
	14: from /Users/hex22a/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	13: from /Users/hex22a/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	12: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	 9: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	 8: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 2: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 1: from /Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
/Users/hex22a/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/helper/adb_helper.rb:55:in `load_all_devices': [!] undefined method `shellescape' for nil:NilClass (NoMethodError)

**Comment by hauthorn** [comment]
@janpio sorry but I think this error is not only screengrab, but pretty much anything that tries to use adb, and therefore fastlane on Android is broken as a result.

**Comment by 20ali20** [comment]
Same here. any solutions ?

**Comment by 20ali20** [comment]
I tried to look into it a bit. 
it says it can not find a method called `shellescape` which is a function from `shellwords` library. So I tried to import it directly to in the file and then another error shows.

**Comment by karottenreibe** [comment]
It seems to me from the code that this is caused by fastlane not being able to find your android SDK. for me the problem is fixed wtih

```bash
ANDROID_HOME=/path/to/sdk bundle exec fastlane screenshots
```

unfortunately the `android_home` keyword arg to `capture_android_screenshots` has no effect, which is where I'd rather set this. fastlane could also read this value from the `local.properties` gradle file where the `sdk.dir` property has to be defined anyways.

**Comment by hauthorn** [comment]
@karottenreibe that works for me. How come this has started to fail now? Been using my current setup for several months with now issue.

**Comment by 20ali20** [comment]
> @karottenreibe that works for me. How come this has started to fail now? Been using my current setup for several months with now issue.

The only reason I can think of is Catalina O.S. Prior to the upgrade I didn't have this issue

**Comment by hex22a** [comment]
adding `ANDROID_HOME` environment variable worked for me!

**Comment by mortenholmgaard** [comment]
It does not solve it for me setting the Android_Home path:
```
    ENV["ANDROID_HOME"] = ".../Android/sdk"
    capture_android_screenshots(...)
```
I get this:

> The `adb` command could not be found relative to your provided ANDROID_HOME at .../Android/sdk
> Please ensure that the Android SDK is installed and the platform-tools directory is present

But it is present correctly there. for fun it tried something invalid like this
```
    ENV["ANDROID_HOME"] = ".../Android/sdk/platform-tools" 
// or 
    ENV["ANDROID_HOME"] = ".../Android"
```

Then it is found by other means:
```
Using `adb` found at ...\Android\sdk\platform-tools/adb.EXE which is not within the specified ANDROID_HOME at .../Android/
[22:12:01]: Using `aapt` found at ...\Android\sdk\build-tools\21.1.2\aapt.EXE which is not within the specified ANDROID_HOME at .../Android/
```

But then fails as exepcted but later:
`C:/tools/ruby26/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - .../Android/platform-tools/adb devices -l (Errno::ENOENT)`

**So no matter what I set the ANDROID_HOME to I can't get screengrab to work.**
