### ISSUE TITLE
[regression] firebase_app_distribution action is broken in 2.161.0

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#17339]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.161.0`
- Last working version: `2.160.0`

### Regression Description
`firebase_app_distribution` action is not working since the last update: it seems that `groups` parameter/contents is processed case-sensitive (probably) and the firebase backend returns error.
There is an [issue](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/159) in action repository where other developers confirms that downgrading to 2.160.0 solves their issue, so this is not a regression in the action itself.
Maybe it is regressed by #17256?

##### Complete output when running fastlane, including the stack trace and command used
This is the regressed fastlane output:
<details>
  <pre>
[14:02:36]: ---------------------------------------
[14:02:36]: --- Step: firebase_app_distribution ---
[14:02:36]: ---------------------------------------
[14:02:36]: Authenticating with FIREBASE_TOKEN environment variable
[14:02:36]: 🔐 Authenticated successfully.
[14:02:38]: ⌛ Uploading the IPA.
[14:02:53]: ✅ Uploaded the IPA.
[14:02:53]: ✅ No release notes passed in. Skipping this step.
[14:02:53]: -------------------
[14:02:53]: --- Step: is_ci ---
[14:02:53]: -------------------
[14:02:53]: --------------------------
[14:02:53]: --- Step: fastlane env ---
[14:02:53]: --------------------------
...
| 💥   | firebase_app_distribution                                     | 20          |
| 49   | is_ci                                                         | 0           |
| 50   | fastlane env                                                  | 2           |
+------+---------------------------------------------------------------+-------------+

[09:55:34]: fastlane finished with errors

[!] Could not enable access for testers. Check that the groups exist and the tester emails are formatted correctly 
Emails:  
Groups: ["ios-testers"]
script returned exit code 1

</pre>
</details>

And this is the output on 2.160.0:
<details>
  <pre>[13:50:30]: ---------------------------------------
[13:50:30]: --- Step: firebase_app_distribution ---
[13:50:30]: ---------------------------------------
[13:50:30]: Authenticating with FIREBASE_TOKEN environment variable
[13:50:30]: 🔐 Authenticated successfully.
[13:50:32]: ⌛ Uploading the IPA.
[13:50:44]: ✅ Uploaded the IPA.
[13:50:44]: ✅ No release notes passed in. Skipping this step.
[13:50:47]: ✅ Added testers/groups.
[13:50:47]: 🎉 App Distribution upload finished successfully.
[13:50:47]: -------------------------------------------
[13:50:47]: --- Step: upload_symbols_to_crashlytics ---
[13:50:47]: -------------------------------------------
</pre>
</details>

There is no difference in Fastfile between these two launches. They both call
```ruby
		firebase_app_distribution(app: app_id, groups: "ios-testers", debug: true)	
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.4.9                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.9/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.9/lib                |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.161.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_management       | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-firebase_app_distribution | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.1.0        |
| bundler                                   | 1.17.3       |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| concurrent-ruby                           | 1.1.7        |
| i18n                                      | 0.9.5        |
| minitest                                  | 5.14.2       |
| thread_safe                               | 0.3.6        |
| tzinfo                                    | 1.2.7        |
| activesupport                             | 4.2.11.3     |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| httpclient                                | 2.8.3        |
| json                                      | 2.3.1        |
| algoliasearch                             | 1.27.4       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.376.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.108.0      |
| aws-sdk-kms                               | 1.38.0       |
| aws-sdk-s3                                | 1.81.1       |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| fuzzy_match                               | 2.0.4        |
| nap                                       | 1.1.0        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.13.1       |
| ethon                                     | 0.12.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.9.3        |
| cocoapods-deintegrate                     | 1.0.4        |
| cocoapods-downloader                      | 1.4.0        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.0        |
| cocoapods-stats                           | 1.1.0        |
| cocoapods-trunk                           | 1.5.0        |
| cocoapods-try                             | 1.2.0        |
| colored2                                  | 3.1.2        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.6.6        |
| ruby-macho                                | 1.4.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.18.0       |
| cocoapods                                 | 1.9.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.0.0        |
| excon                                     | 0.76.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 1.0.1        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.1       |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.3.3        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.0       |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.2        |
| mime-types-data                           | 3.2020.0512  |
| mime-types                                | 3.3.1        |
| multi_xml                                 | 0.6.0        |
| httparty                                  | 0.18.1       |
| fastlane-plugin-firebase_management       | 1.1.0        |
| mustache                                  | 1.1.1        |
| open4                                     | 1.3.4        |
| redcarpet                                 | 3.5.0        |
| sassc                                     | 2.4.0        |
| sqlite3                                   | 1.4.2        |
| liferaft                                  | 0.0.6        |
| xcinvoke                                  | 0.3.0        |
| jazzy                                     | 0.13.5       |
</details>
*generated on:* **2020-09-29**
</details>

**Comment by rubnov** [comment]
I'm having trouble with the `firebase_distribution_plugin` as well. Getting this error in the console: 

```
bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.6.0/bin/fastlane)
Faraday::BadRequestError: [!] the server responded with status 400
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:16:in `on_complete'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
  /usr/local/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.2/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:68:in `post_notes'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.2/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:82:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
  /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<top (required)>'
```

I removed the `notes` field from `firebase_app_distribution` call in my Fastfile but it made no difference. Still getting the same error. Not sure if this is a Fastlane or Firebase plugin issue though.

**Comment by PatrickDotStar** [comment]
Same issue here. Also getting `Faraday::BadRequestError: [31m[!] the server responded with status 400`

**Comment by barchinsky** [comment]
I'm also experiencing the same issue with with 0.2.2

**Comment by LemonSpike** [comment]
Same here

**Comment by jasin755** [comment]
+1

**Comment by olbartek** [comment]
+1

**Comment by viikufa** [comment]
+1

**Comment by jasin755** [comment]
Downgrade to 2.160 helps

**Comment by ChawkiOS** [comment]
+1

**Comment by leHomard** [comment]
+1

**Comment by Asuard** [comment]
+1

**Comment by garry-jeromson** [comment]
And another.

**Comment by yurijdvornyk** [comment]
+1

**Comment by nthegedus** [comment]
+1

**Comment by georgegal** [comment]
I have a similar issue AppCenter plugin.
```
ERROR [2020-09-29 15:14:31.67]: fastlane finished with errors
DEBUG [2020-09-29 15:14:31.67]: All plugins are up to date
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/interface.rb:184:in `abort_with_message!': [!] Upload aborted (FastlaneCore::Interface::FastlaneCommonException)
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-appcenter-1.9.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:217:in `run_release_upload'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-appcenter-1.9.0/lib/fastlane/plugin/appcenter/actions/appcenter_upload_action.rb:355:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:256:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:154:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by theomendes** [comment]
+1

**Comment by chadrickman** [comment]
+1

**Comment by nthegedus** [comment]
I'm using
```
firebase_app_distribution v0.2.2
fastlane v2.161.0
```

This is the error response after running **firebase_app_distribution**
`the server responded with status 400`

But in Firebase App Distribution console, the APKs are appearing like the image below, and I have to release manually.
The release notes are not working as expected too

<img width="713" alt="firebase" src="https://user-images.githubusercontent.com/1063383/94574298-58c36280-0249-11eb-9ac3-3657e8db5c23.png">

**Comment by 8of** [comment]
Can confirm what @nthegedus stated.
The same behavior for android (.apk) and iOS (.ipa) files.

**Comment by joshdholtz** [comment]
Looking into what could have caused this! Will try to have a fix soon.

**Comment by joshdholtz** [comment]
I think this might be the cause - https://github.com/fastlane/fastlane/pull/17218

This was a fix to another problem but it looks the firebase plugin might have been relying on this 🤔 I’m unsure but that is what I’m going to look into first.

**Comment by sbo-nemlig** [comment]
> Can confirm what @nthegedus stated.
> Would like to add info: we see the same behavior for android (.apk) and iOS (.ipa) files.
> Full error message:
> 
> ```
> Could not enable access for testers. Check that the groups exist and the tester emails are formatted correctly 
> ```

Also have this issue but this, started this morning also on older versions of fastlane. Looks to be a issue on firebase end

**Comment by brownoxford** [comment]
This is an issue with the monkey patch for net http request. Previous version had this:

```ruby
module Net
  class HTTPGenericRequest
    def supply_default_content_type
      return if content_type
    end
  end
end
```

Note that there is never any default content type supplied... the code returns if one is already set and does nothing otherwise.

New code is this:

```ruby
module NetHTTPGenericRequestMonkeypatch
  def supply_default_content_type
    # Return no content type if we communicating with an apple.com domain
    return if !self['host'].nil? && self['host'].end_with?('.apple.com')

    # Otherwise use the default implementation
    super
  end
end
```

Note the call to `super`, which sets a default content type of `application/x-www-form-urlencoded` if none is already set. This is probably "correct" behavior, but breaks all existing code that expects no content type to be set if none was specified.

In particular, the `firebaseappdistribution.googleapis.com` api endpoint used by `firebase_app_distribution` does not work with a content type of `application/x-www-form-urlencoded`. It does work with `application/json` and `text/plain` though.

I think the right solution here is for `firebase_app_distribution` to set the right content type when making requests.

**Comment by joshdholtz** [comment]
@sbo-nemlig @brownoxford Yup yup, I’m working on a fix for this right now! I’ll keep you all updated when I have something ready

**Comment by joshdholtz** [comment]
Fixed in https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/160 by @brownoxford ❤️  I will comment when the new gem is out.

**Comment by lfkellogg** [comment]
The fix is now available in plugin [v0.2.3](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.3).

**Comment by sleman** [comment]
Running `fastlane update_plugins` doesn't show the update for me.

```
$ fastlane update_plugins
[✔] 🚀
[13:11:23]: fastlane detected a Gemfile in the current directory
[13:11:23]: However, it seems like you didn't use `bundle exec`
[13:11:23]: To launch fastlane faster, please use
[13:11:23]:
[13:11:23]: $ bundle exec fastlane update_plugins
[13:11:23]:
[13:11:23]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-------------------------------------------+---------+----------------------------------+
|                                      Used plugins                                      |
+-------------------------------------------+---------+----------------------------------+
| Plugin                                    | Version | Action                           |
+-------------------------------------------+---------+----------------------------------+
| fastlane-plugin-firebase_app_distribution | 0.2.2   | firebase_app_distribution_login  |
|                                           |         | firebase_app_distribution        |
+-------------------------------------------+---------+----------------------------------+

Updating plugin dependencies...
Successfully updated plugins
```

**Comment by Sega-Zero** [comment]
Confirm the fix. Thanks!

**Comment by kungfuslippers** [comment]
> Downgrade to 2.160 helps

I'm still seeing a similar issue after the fix when using fastlane 2.161.0 and fastlane-plugin-firebase_app_distribution 0.2.3 where I get a 403 Forbidden.

How do you downgrade to fastlane 2.160 ?

**Comment by kungfuslippers** [comment]
Have tried downgrading to fastlane 2.160.0 with fastlane-plugin-firebase_app_distribution 0.2.3 and still get the same issue with a 403 forbidden

Here is my fastlane env updated to the most recent version.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.rvm/gems/ruby-2.5.0/bin/fastlane         |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0                                        |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |



### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.161.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.2.0        |
| executable-hooks                          | 1.6.0        |
| bundler-unload                            | 1.0.2        |
| rubygems-bundler                          | 1.4.5        |
| bundler                                   | 2.1.4        |
| rake                                      | 13.0.1       |
| CFPropertyList                            | 3.0.2        |
| public_suffix                             | 4.0.6        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.1.0        |
| aws-partitions                            | 1.378.0      |
| aws-sigv4                                 | 1.2.2        |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.0      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.82.0       |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.20       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.6.1        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.6        |
| emoji_regex                               | 3.0.0        |
| excon                                     | 0.76.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 1.0.1        |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.0.0        |
| fastimage                                 | 2.2.0        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.2.2        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.1       |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.0.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.38.0       |
| google-cloud-env                          | 1.3.3        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.0       |
| json                                      | 2.3.1        |
| mini_magick                               | 4.10.1       |
| plist                                     | 3.5.0        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.7.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.18.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.2.3        |
</details>


*generated on:* **2020-10-01**
</details>

Build error is here:

	38: from /Users/mcawley/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
	37: from /Users/mcawley/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
	36: from /Users/mcawley/.rvm/gems/ruby-2.5.0/bin/fastlane:23:in `<main>'
	35: from /Users/mcawley/.rvm/gems/ruby-2.5.0/bin/fastlane:23:in `load'
	34: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
	33: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	32: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	31: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	30: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	29: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	28: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	27: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	26: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	25: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	24: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	23: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	22: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	21: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	20: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	19: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	18: from Fastfile:84:in `block (2 levels) in parsing_binding'
	17: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	16: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	15: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	14: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	13: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	12: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	11: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	10: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:31:in `run'
	 9: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:143:in `upload'
	 8: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:97:in `get_upload_token'
	 7: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
	 6: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
	 5: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	 4: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	 3: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
	 2: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
	 1: from /Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
/Users/mcawley/.rvm/gems/ruby-2.5.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:20:in `on_complete': [!] the server responded with status 403 (Faraday::ForbiddenError)

**Comment by kungfuslippers** [comment]
> The fix is now available in plugin [v0.2.3](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.3).

Doesn't work for me.

**Comment by lfkellogg** [comment]
@kungfuslippers This looks like a different issue: a 403 generally indicates an authentication problem, and it looks like it's failing on a request that wasn't affected by this bug.

Can you confirm that the Google account you are authenticating with has access to the Firebase app? You can also create a new issue in the plugin repo and we'll figure out what's going on: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution

**Comment by Furman950** [comment]
Hey guys I'm using

- fastlane 1.60.0
- fastlane-plugin-firebase_app_distribution 0.2.3

but I am still getting back `[!] the server responded with status 400 (Faraday::BadRequestError)`

do you guys have any suggestions?

**Comment by kungfuslippers** [comment]
> @kungfuslippers This looks like a different issue: a 403 generally indicates an authentication problem, and it looks like it's failing on a request that wasn't affected by this bug.
> 
> Can you confirm that the Google account you are authenticating with has access to the Firebase app? You can also create a new issue in the plugin repo and we'll figure out what's going on: https://github.com/fastlane/fastlane-plugin-firebase_app_distribution

Yes, I think you were right about the authentication. I suspect the firebase_cli_token had become invalidated somehow as when I commented it out in the  firebase_app_distribution(..) section of my fastfile it attempted to use a cached version and completely successfully.

**Comment by lfkellogg** [comment]
@Furman950 There are some other cases where the API can return 400, I suspect there might be something else going on. Can you please open up a new ticket in the plugin repo (https://github.com/fastlane/fastlane-plugin-firebase_app_distribution), and include the full fastlane output and the `fastlane_app_distribution` action call in your Fastfile?
