### ISSUE TITLE
Error upload to AppStore TestFlight using fastlane v2.198.0 (An error occurred while processing the json request. (1268)) using Azure Devops

### ISSUE THREAD

**Issue by LukasP94** [fastlane/fastlane#19613]
### Issue Description
Can not upload .ipa to TestFlight with version 2.198.0 but when I switch back to 2.197.0 it working...

##### Complete output when running fastlane, including the stack trace and command used

2021-11-16T12:58:46.6255080Z ==============================================================================
2021-11-16T12:58:46.6255470Z Task         : Apple App Store Release
2021-11-16T12:58:46.6255790Z Description  : Release an app to TestFlight or the Apple App Store
2021-11-16T12:58:46.6256080Z Version      : 1.189.0
2021-11-16T12:58:46.6256320Z Author       : Microsoft Corporation
2021-11-16T12:58:46.6257840Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store)
2021-11-16T12:58:46.6258310Z ==============================================================================
2021-11-16T12:58:49.1510240Z [command]/usr/local/opt/ruby@2.7/bin/gem install fastlane
2021-11-16T12:59:23.0450540Z Successfully installed fastlane-2.198.0
2021-11-16T12:59:23.0451520Z Parsing documentation for fastlane-2.198.0
2021-11-16T12:59:23.0457530Z Installing ri documentation for fastlane-2.198.0
2021-11-16T12:59:23.0458260Z Done installing documentation for fastlane after 29 seconds
2021-11-16T12:59:23.0458640Z 1 gem installed
2021-11-16T12:59:23.0818030Z [command]/usr/local/opt/ruby@2.7/bin/gem update fastlane -i /Users/runner/.gem-cache
2021-11-16T12:59:26.7363040Z Updating installed gems
2021-11-16T12:59:26.7464960Z Nothing to update
2021-11-16T12:59:26.7854080Z ##[warning]You specified releaseNotes - so you need to provide fastlane session, app specific password only won't work
2021-11-16T12:59:26.7890900Z [command]/usr/local/lib/ruby/gems/2.7.0/bin/fastlane pilot upload --api_key_path /Users/runner/work/_temp/api_keyMyKey.json -i /Users/runner/work/r1/a/$(Pipeline.Workspace)/ios_drop/myIpa.ipa --changelog MyChages
2021-11-16T12:59:26.7896820Z - App framework updated to version 2.x -a com.xxx.xxx --distribute_external true --groups AppGroups
2021-11-16T12:59:29.2059060Z [12:59:29]: [33mGet started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
2021-11-16T12:59:34.0076090Z [12:59:34]: Sending anonymous analytics information
2021-11-16T12:59:34.0077420Z [12:59:34]: Learn more at https://docs.fastlane.tools/#metrics
2021-11-16T12:59:34.0079650Z [12:59:34]: No personal or sensitive data is sent.
2021-11-16T12:59:34.0080130Z [12:59:34]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
2021-11-16T12:59:34.0341370Z [12:59:34]: Creating authorization token for App Store Connect API
2021-11-16T12:59:39.6942440Z [12:59:39]: Ready to upload new build to TestFlight (App: 1************)...
2021-11-16T12:59:41.0207620Z [12:59:41]: Going to upload updated app to App Store Connect
2021-11-16T12:59:41.0211430Z [12:59:41]: This might take a few minutes. Please don't interrupt the script.
2021-11-16T13:00:45.2154010Z [13:00:45]: Transporter transfer failed.
2021-11-16T13:00:45.2255890Z [13:00:45]: 
2021-11-16T13:00:45.2357840Z [13:00:45]: **An error occurred while processing the json request. (1268)**
2021-11-16T13:00:45.3766610Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main> DBG-X:   parameter ErrorMessage = An error occurred while processing the json request. (1268)
2021-11-16T13:00:45.3814960Z 
2021-11-16T13:00:45.3817380Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
2021-11-16T13:00:45.3822960Z 
2021-11-16T13:00:45.3825170Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main> DBG-X:   parameter Success = false
2021-11-16T13:00:45.3826310Z 
2021-11-16T13:00:45.3835020Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main> ERROR: An error occurred while processing the json request. (1268)
2021-11-16T13:00:45.3835420Z 
2021-11-16T13:00:45.3836250Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main> DBG-X: The error code is: 1268
2021-11-16T13:00:45.3836560Z 
2021-11-16T13:00:45.3837470Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:44 UTC] <main>  INFO: Done performing authentication.
2021-11-16T13:00:45.3837790Z 
2021-11-16T13:00:45.3838090Z [13:00:45]: [iTMSTransporter] 
2021-11-16T13:00:45.3838250Z 
2021-11-16T13:00:45.3838540Z [13:00:45]: [iTMSTransporter] 
2021-11-16T13:00:45.3838690Z 
2021-11-16T13:00:45.3838950Z [13:00:45]: [iTMSTransporter] 
2021-11-16T13:00:45.3839110Z 
2021-11-16T13:00:45.3839430Z [13:00:45]: [iTMSTransporter] Package Summary:
2021-11-16T13:00:45.3839630Z 
2021-11-16T13:00:45.3839890Z [13:00:45]: [iTMSTransporter]  
2021-11-16T13:00:45.3840050Z 
2021-11-16T13:00:45.3840460Z [13:00:45]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
2021-11-16T13:00:45.3840750Z 
2021-11-16T13:00:45.3841890Z [13:00:45]: [iTMSTransporter] 	/var/folders/24/8k4gn/T/myIpa.ipa (/var/folders/24/8k4gn/T/DeveloperAPIUpload****/***.itmsp) - Error Messages:
2021-11-16T13:00:45.3842470Z 
2021-11-16T13:00:45.3842870Z [13:00:45]: [iTMSTransporter] 		An error occurred while processing the json request. (1268)
2021-11-16T13:00:45.3843140Z 
2021-11-16T13:00:45.3843900Z [13:00:45]: [iTMSTransporter] [2021-11-16 13:00:45 UTC] <main> DBG-X: Returning 1
2021-11-16T13:00:45.3844190Z 
2021-11-16T13:00:45.3844500Z [13:00:45]: iTunes Transporter output above ^
2021-11-16T13:00:45.3844930Z [13:00:45]: An error occurred while processing the json request. (1268)
2021-11-16T13:00:45.3845460Z Return status of iTunes Transporter was 1: An error occurred while processing the json request. (1268)
2021-11-16T13:00:45.3846420Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
2021-11-16T13:00:45.4166640Z 
2021-11-16T13:00:45.4167740Z [!] Error uploading ipa file: 
2021-11-16T13:00:45.4168310Z  
2021-11-16T13:00:45.4488750Z ##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1

**Comment by joshdholtz** [comment]
@LukasP94 Thank you for the report! Looking into the bug and what the fix should be 😬

**Comment by joshdholtz** [comment]
@LukasP94 Are you able to run this with `--verbose` flag on and send me the logs? Feel free to email me them if you don't want to post them here at `me` `AT` `joshholtz` `DOT` `com` 🙏

**Comment by robbypontas** [comment]
Same with me,

it gave me error:

[iTMSTransporter] [2021-11-17 14:28:54 WIB] <main> ERROR: The '-assetFile' option must specify a file, not a directory.

**Comment by maxencehenneron** [comment]
Encountered the same issue. Reverting to 2.197.0 works. Same error as the message above.

**Comment by sk-chanch** [comment]
+1

**Comment by ninjz** [comment]
+1

**Comment by joshdholtz** [comment]
> Same with me,
> 
> it gave me error:
> 
> [iTMSTransporter] [2021-11-17 14:28:54 WIB]
> 
> ERROR: The '-assetFile' option must specify a file, not a directory.

This is super useful! Thank you 😊 Will have a fix out for this soon!

**Comment by joshdholtz** [comment]
And just a little favor it ask 😇 

And if any `+1`s in the future could get turned into a 👍 on the issue that would be 🔥 Its hard to look for relevant information in the comments when there are a lot of `+1`s 😉

**Comment by joshdholtz** [comment]
✨ Official Update

#19620 has a fix if anybody is able to try that out ❤️

**Comment by robbypontas** [comment]
@joshdholtz tried #19620 
it was successfully uploaded but contain some below warnings, 
and contain red log also, is that ok?

the logs:
...
[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main >  INFO: Upload mode selected.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/Payload because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/SwiftSupport because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/Symbols because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/myProject.ipa because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > ERROR: The directory: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa does NOT have any valid iTMS packages.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/Payload because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/SwiftSupport because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/Symbols because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DEBUG: Ignoring file: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa/myProject.ipa because it is NOT an iTMS package.

[20:55:19]: [iTMSTransporter] 

[20:55:19]: [iTMSTransporter] 

[20:55:19]: [iTMSTransporter] 

[20:55:19]: [iTMSTransporter] Package Summary:

[20:55:19]: [iTMSTransporter] [2021-11-17 20:55:18 WIB] < main > DBG-X: Returning 0

[20:55:19]: iTunes Transporter output above ^
**red color -> [20:55:19]: The directory: /var/folders/15/wc_5y2ks0ks38zpv8kcqgk3r0000gn/T/myProject.ipa does NOT have any valid iTMS packages.** 
[20:55:19]: Although errors occurred during execution of iTMSTransporter, it returned success status.
[20:55:19]: ------------------------------------------------------------------------------------------------------------------
[20:55:19]: --- Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online. ---
[20:55:19]: ------------------------------------------------------------------------------------------------------------------
[20:55:19]: Successfully uploaded the new binary to App Store Connect
...
...
[21:07:45]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[21:08:16]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
[21:08:47]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)

**Comment by joshdholtz** [comment]
@robbypontas Do you happen to have a line in your console that looks something like...

```sh
xcrun iTMSTransporter -m upload -u me@joshholtz.com -p @env:ITMS_TRA
NSPORTER_PASSWORD -assetFile /var/folders/cf/2xvwkyns7s5_4cfdqcmjf2740000gn/T/CrunchyGIF.pkg -k 100000 -itc_provider YOUR_PROVIDER_NUMBER 2>&1
```

I'm curious what your `-assetFile` or `-f` path is in your `xcrun iTMSTransporter -m upload` command 🤔

**Comment by scotttball** [comment]
@joshdholtz I had this issue. I had to manually specify the `ipa` path within deliver to get it to actually work.

**Comment by joshdholtz** [comment]
@scotttball Yikes 😱 Do you have logs that you can share with me from the start of deliver to the end where it failed? I'm curious what was getting passed into deliver in term of the IPA path that was causing it to go weird.

Also, do you happen to know which commit you tried this with? I just added a new commit 3 hours ago that I think _should_ have solved this for you 😬

**Comment by scotttball** [comment]
@joshdholtz It was with v2.198.0. I don't have the `--verbose` logs that I can show. I know it's not much help in diagnosing the issue. Since I deployed the app already to production, I can't provide the logs since it's a production deployment lane and I can't run those locally. From what I could tell, it seemed like it was uploading the whole directory up. Apple rejected it for not having "thinning" enabled (which is probably wrong since it's been fine before). 

I looked at your fix and it seems like it handles my theory. I haven't tested it yet, but next time I do a production deploy, I'll watch for it.

**Comment by joshdholtz** [comment]
@scotttball Ohhhhh, sorry! I thought you were on the PR branch 🤦‍♂️ I might just ship that PR because I don't think things can get worse 😅

**Comment by youssefali424** [comment]
it happened on 2.198.1 as well but this time with no clear error, had to downgrade to 2.197.0, not sure I ran it with verbose only shows this "An error occurred while processing the json request. (1268)" no other error, made sure that the version working on ci was the last "2.198.1"

**Comment by ED220-RitM** [comment]
Happening for me as well. But since this is only happening for a very small minority of our apps, I am suspecting that some special characters in the ipa name might be the issue. The Pipelines that are failing now worked perfectly fine about a month ago, so this might be due to a recent change.

The special characters i have seen are german ones like öäü

Just in case it is relevant: The IPA file is provided via the `-i` flag to the `pilot upload` command

**Comment by youssefali424** [comment]
yes or Arabic characters as well might be the issue, but what is guaranteed is that the issue started happening on 2.198 and wasn't completely fixed in 2.198.1 as 2.197.0 is working fine

**Comment by Aquilosion** [comment]
I'm also getting failed uploads with IPAs which contain special characters. Is there a separate issue which tracks this? Otherwise I guess this one needs to be reopened.

**Comment by ED220-RitM** [comment]
@Aquilosion if you can get a (new) debug log, feel free to open a new Issue. I think that might be better anyway, if those 2 Issues are actually separate ones

**Comment by ricsantos** [comment]
I'm getting this error too, have many localisations if the special character issue is true. Fastlane 2.198.1.

**Comment by ricsantos** [comment]
Updated to fastlane 2.199.0 and it worked 🎉

**Comment by sk-chanch** [comment]
fastlane 2.199.0 error upload in my case use &#x2007; with app name and use app name for name of .ipa  file  upload to app store when use deliver get error 1268 after change .ipa file name to app bundle id it worked not error though before 2.198.0 not found error 1268

**Comment by dunklesToast** [comment]
Encountered the same issue. Appended full Logs, maybe they help.

<details>
<summary>Logs</summary>
<pre>
[23:04:49]: -------------------
[23:04:49]: --- Step: pilot ---
[23:04:49]: -------------------
[23:04:49]: Creating authorization token for App Store Connect API
[23:04:51]: Ready to upload new build to TestFlight (App: 1598893449)...
[23:04:52]: Going to upload updated app to App Store Connect
[23:04:52]: This might take a few minutes. Please don't interrupt the script.
[23:05:04]: iTunes Transporter successfully finished its job
[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main>  INFO: Upload mode selected.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/RIDEN.ipa because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/BCSymbolMaps because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/Payload because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/SwiftSupport because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> ERROR: The directory: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa does NOT have any valid iTMS packages.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/RIDEN.ipa because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/BCSymbolMaps because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/Payload because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DEBUG: Ignoring file: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa/SwiftSupport because it is NOT an iTMS package.

[23:05:04]: [iTMSTransporter] 

[23:05:04]: [iTMSTransporter] 

[23:05:04]: [iTMSTransporter] 

[23:05:04]: [iTMSTransporter] Package Summary:

[23:05:04]: [iTMSTransporter] [2021-12-17 23:05:04 CET] <main> DBG-X: Returning 0

[23:05:04]: iTunes Transporter output above ^
[23:05:04]: The directory: /var/folders/7g/y39pzkk153s_j_kls8dyf3_80000gq/T/RIDEN.ipa does NOT have any valid iTMS packages.
[23:05:04]: Although errors occurred during execution of iTMSTransporter, it returned success status.
[23:05:04]: -------------------------------------------------------------------------------------------
[23:05:04]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
[23:05:04]: -------------------------------------------------------------------------------------------
[23:05:04]: Successfully uploaded the new binary to App Store Connect
[23:05:04]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[23:05:04]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
[23:05:04]: Waiting for processing on... app_id: 1598893449, app_version: 1.0, build_version: 4, platform: IOS
[23:05:05]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
[23:05:05]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
</pre>
</details>

Fastlane got stuck for 30min on `Waiting for the build to show up in the build list` and the build didn't even showed up on App Store Connect for processing. Going back to `2.197.0` resolved it for me - if you need more info, I'd be happy to provide it!

**Comment by ArtFeel** [comment]
Same issue with fastlane `2.199.0`, iTMSTransporter returned success status, but there is no build in Appstore Connect

<details><summary>Logs</summary>
<p>

```
INFO [2021-12-23 14:07:17.27]: ----------------------------------
INFO [2021-12-23 14:07:17.27]: --- Step: upload_to_testflight ---
INFO [2021-12-23 14:07:17.27]: ----------------------------------
INFO [2021-12-23 14:07:17.27]: Login to App Store Connect (email@domain.com)
Reading keychain entry, because either user or password were empty
Loading session from '/Users/jenkins/.fastlane/spaceship/email@domain.com/cookie'
Looking for App Store Connect Team with name TeamName
Looking for App Store Connect Team with ID TeamID
INFO [2021-12-23 14:07:19.54]: Login successful
DEBUG [2021-12-23 14:07:19.54]: App identifier (com.identifier.app)
INFO [2021-12-23 14:07:27.41]: Ready to upload new build to TestFlight (App: 565967395)...
DEBUG [2021-12-23 14:07:27.45]: App Platform (ios)
INFO [2021-12-23 14:07:29.14]: Wrote XML data to '/var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/d20211223-63481-qcqw1b/565967395-a38f942d-7eea-4674-938f-484f07398794.itmsp'
INFO [2021-12-23 14:07:29.14]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
DEBUG [2021-12-23 14:07:29.64]: ITMS_TRANSPORTER_PASSWORD=YourPassword xcrun iTMSTransporter -m provider -u email@domain.com -p @env:ITMS_TRANSPORTER_PASSWORD 2>&1
DEBUG [2021-12-23 14:07:34.33]: [Transporter]: INFO: Configuring logging...
DEBUG [2021-12-23 14:07:34.34]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2021-12-23 14:07:36.08]: [Transporter]: DEBUG: SMART-CLIENT: initializing data center locking ops: [authenticateForSession, validateAssets]
DEBUG [2021-12-23 14:07:36.22]: [Transporter]: DEBUG: SMART-CLIENT: initializing data centers with: [contentdelivery02.itunes.apple.com, contentdelivery01.itunes.apple.com]
DEBUG [2021-12-23 14:07:36.22]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.3.0]
DEBUG [2021-12-23 14:07:36.22]: [Transporter]: INFO: OS identifier: Mac OS X 11.6.2 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2021-12-23 14:07:36.23]: [Transporter]: INFO: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 3459M free, 32768M total (Swap) 0 free, 0 total
DEBUG [2021-12-23 14:07:36.23]: [Transporter]: INFO: Provider mode selected.
DEBUG [2021-12-23 14:07:36.23]: [Transporter]: DBG-X: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 3459M free, 32768M total (Swap) 0 free, 0 total
DEBUG [2021-12-23 14:07:36.23]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 11.6.2 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-12-23T14:07:36+02:00
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.226292945
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter TransporterArguments = -m provider -u email@domain.com -p **hidden value**
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = provider
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: INFO: id = 20211223140736-322
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); current data center is null
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); iterator was null, setting it
DEBUG [2021-12-23 14:07:36.25]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); setting current data center to: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:36.26]: [Transporter]: INFO: iTMSTransporter Correlation Key: c0fd3f0a-519c-4605-ba7f-427934f66f03-0001
DEBUG [2021-12-23 14:07:36.26]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DEBUG: SMART-CLIENT: pinning data center to: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter TxHeaders = {jenga=true}
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter ShouldUseFeatures = (null)
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter SessionExpiration = 2021-12-27T12:07:36.892Z
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter SessionId = CICrDBIQa5YSS/3oRcWlpMGsvItqsw==
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter ShouldUseRESTAPIs = false
DEBUG [2021-12-23 14:07:36.95]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: INFO: Performing providers request ...
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X: Memory: [JVM] 990M free, 1024M total, 2048M max [System] (Physical) 3456M free, 32768M total (Swap) 0 free, 0 total
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X: Using operation named: providersWithArguments
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 11.6.2 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-12-23T14:07:36+02:00
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter TransporterArguments = -m provider -u email@domain.com -p **hidden value**
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = provider
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: INFO: id = 20211223140736-956
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); using pinned data center = contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: INFO: iTMSTransporter Correlation Key: c0fd3f0a-519c-4605-ba7f-427934f66f03-0001
DEBUG [2021-12-23 14:07:36.96]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X:   parameter TeamName = TeamID1
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X:   parameter TeamName2 = TeamID2
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X:   parameter TeamName3 = TeamID3
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X:   parameter TeamName4 = TeamID4
DEBUG [2021-12-23 14:07:37.52]: [Transporter]: DBG-X:   parameter TeamName5 = TeamID5
INFO [2021-12-23 14:07:37.54]: iTunes Transporter successfully finished its job
DEBUG [2021-12-23 14:07:37.54]: [Transporter]: DBG-X: Returning 0
DEBUG [2021-12-23 14:07:37.68]: Inferred provider id TeamID1 for team TeamName.
INFO [2021-12-23 14:07:37.68]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
INFO [2021-12-23 14:07:38.03]: Going to upload updated app to App Store Connect
INFO [2021-12-23 14:07:38.03]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2021-12-23 14:07:38.03]: ITMS_TRANSPORTER_PASSWORD=YourPassword xcrun iTMSTransporter -m upload -u email@domain.com -p @env:ITMS_TRANSPORTER_PASSWORD -f /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa -k 100000 -itc_provider TeamID1 2>&1
DEBUG [2021-12-23 14:07:43.92]: [Transporter]: INFO: Configuring logging...
DEBUG [2021-12-23 14:07:43.93]: [Transporter]: INFO: Logging level set to eXtreme
DEBUG [2021-12-23 14:07:46.14]: [Transporter]: DEBUG: SMART-CLIENT: initializing data center locking ops: [authenticateForSession, validateAssets]
DEBUG [2021-12-23 14:07:46.14]: [Transporter]: DEBUG: SMART-CLIENT: initializing data centers with: [contentdelivery02.itunes.apple.com, contentdelivery01.itunes.apple.com]
DEBUG [2021-12-23 14:07:46.14]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [2.3.0]
DEBUG [2021-12-23 14:07:46.14]: [Transporter]: INFO: OS identifier: Mac OS X 11.6.2 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2021-12-23 14:07:46.14]: [Transporter]: INFO: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 3427M free, 32768M total (Swap) 0 free, 0 total
DEBUG [2021-12-23 14:07:46.15]: [Transporter]: DBG-X: Memory: [JVM] 997M free, 1024M total, 2048M max [System] (Physical) 3427M free, 32768M total (Swap) 0 free, 0 total
DEBUG [2021-12-23 14:07:46.15]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter BaseVersion = 2.1.0
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter ItcProviderName = TeamID1
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 11.6.2 (x86_64); jvm=14.0.2+12-iTunesOpenJDK-8; jre=14.0.2+12-iTunesOpenJDK-8
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2021-12-23T14:07:46+02:00
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.088404015
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u email@domain.com -p **hidden value** -f /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa -k 100000 -itc_provider TeamID1
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter Version = 2.3.0
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2021-12-23 14:07:46.16]: [Transporter]: INFO: id = 20211223140746-359
DEBUG [2021-12-23 14:07:46.17]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); current data center is null
DEBUG [2021-12-23 14:07:46.17]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); iterator was null, setting it
DEBUG [2021-12-23 14:07:46.17]: [Transporter]: DEBUG: SMART-CLIENT: getCurrent(); setting current data center to: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:46.18]: [Transporter]: INFO: iTMSTransporter Correlation Key: 61987b7b-c899-4248-85d5-5ddad4422d7c-0001
DEBUG [2021-12-23 14:07:46.18]: [Transporter]: DEBUG: SMART-CLIENT: Host HTTP header: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DEBUG: SMART-CLIENT: pinning data center to: contentdelivery02.itunes.apple.com
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter TxHeaders = {jenga=true}
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter ShouldUseFeatures = (null)
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter SessionExpiration = 2021-12-27T12:07:46.790Z
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter SessionId = CICrDBIQs2nKuYHoRnOqRfWRL6ppUQ==
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter ShouldUseRESTAPIs = false
DEBUG [2021-12-23 14:07:46.85]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: INFO: Upload mode selected.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/BCSymbolMaps because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Payload because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/MessagesApplicationExtensionSupport because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/SwiftSupport because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Application.ipa because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/BCSymbolMaps because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Payload because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/MessagesApplicationExtensionSupport because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/SwiftSupport because it is NOT an iTMS package.
DEBUG [2021-12-23 14:07:46.86]: [Transporter]: DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Application.ipa because it is NOT an iTMS package.
INFO [2021-12-23 14:07:46.89]: iTunes Transporter successfully finished its job
DEBUG [2021-12-23 14:07:46.89]: [Transporter]: DBG-X: Returning 0
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Payload because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/MessagesApplicationExtensionSupport because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/SwiftSupport because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Application.ipa because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> ERROR: The directory: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa does NOT have any valid iTMS packages.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/BCSymbolMaps because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Payload because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/MessagesApplicationExtensionSupport because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/SwiftSupport because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DEBUG: Ignoring file: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa/Application.ipa because it is NOT an iTMS package.
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] 
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] 
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] 
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] Package Summary:
WARN [2021-12-23 14:07:47.03]: [iTMSTransporter] [2021-12-23 14:07:46 EET] <main> DBG-X: Returning 0

INFO [2021-12-23 14:07:47.03]: iTunes Transporter output above ^
ERROR [2021-12-23 14:07:47.03]: The directory: /var/folders/cx/50vs14fd2nxbw21xysf0psf00000gn/T/Application.ipa does NOT have any valid iTMS packages.
WARN [2021-12-23 14:07:47.03]: Although errors occurred during execution of iTMSTransporter, it returned success status.
INFO [2021-12-23 14:07:47.03]: -----------------------------------------------------
INFO [2021-12-23 14:07:47.03]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
INFO [2021-12-23 14:07:47.03]: -----------------------------------------------------
```
</p>
</details>

**Comment by henriquenfaria** [comment]
> fastlane 2.199.0 error upload .ipa file in my case use &#x2007; with app name and use app name for name of .ipa file upload to app store when use deliver get error 1268 after change .ipa file name to app bundle id it worked not error though before 2.198.0 not found error 1268

This fixed the error for us. In our case, we were using a special character in the app's name and the solution was to use the bundle id as the ipa's filename.
