### ISSUE TITLE
`handle_two_step_or_factor': [!] Although response from Apple indicated activated Two-step Verification or Two-factor Authentication, spaceship didn't know how to handle this response: 

### ISSUE THREAD

**Issue by mohhomadfarman** [fastlane/fastlane#28633]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Unable to login in falstlane </pre>
</details>

### Environment

<details>
  <pre> [
Exception type: RuntimeError

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Library/Ruby/Gems/2.6.0/bin/fastlane)
/Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/two_step_or_factor_client.rb:23:in `handle_two_step_or_factor': [!] Although response from Apple indicated activated Two-step Verification or Two-factor Authentication, spaceship didn't know how to handle this response: {"phoneNumber"=>{"numberWithDialCode"=>"+1 (•••) •••-••54", "pushMode"=>"sms", "obfuscatedNumber"=>"(•••) •••-••54", "lastTwoDigits"=>"54", "id"=>2}, "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false, "securityCodeCooldown"=>false}, "mode"=>"sms", "type"=>"verification", "authenticationType"=>"hsa2", "noTrustedDevices"=>true, "autoVerified"=>false, "showAutoVerificationUI"=>false, "hideSendSMSCodeOption"=>false, "supervisedChangePasswordFlow"=>false, "hsa2Account"=>true, "restrictedAccount"=>false, "supportsRecovery"=>true, "managedAccount"=>false, "serviceErrors"=>[{"code"=>"-28248", "title"=>"Verification Failed", "message"=>"Verification codes can’t be sent to this phone number at this time. Please try again later.", "suppressDismissal"=>false}]} (RuntimeError)
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/client.rb:591:in `send_shared_login_request'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/tunes/tunes_client.rb:130:in `send_login_request'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/client.rb:955:in `do_login'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/client.rb:394:in `login'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/client.rb:355:in `login'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/spaceauth_runner.rb:20:in `run'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/commands_generator.rb:46:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/commands_generator.rb:52:in `run'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/spaceship/lib/spaceship/commands_generator.rb:15:in `start'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
        from /Users/shuaib/.bundle/ruby/2.6.0/fastlane-ec78d7d81a6a/bin/fastlane:23:in `<top (required)>'
        from /Library/Ruby/Gems/2.6.0/bin/fastlane:23:in `load'
        from /Library/Ruby/Gems/2.6.0/bin/fastlane:23:in `<top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'] </pre>
</details>

**Comment by mohhomadfarman** [comment]
Fixed ; Just Cleaner the user and login again

**Comment by ciregbulem** [comment]
@mohhomadfarman what commands did you run to clean the user and login again?

**Comment by Chuckv01** [comment]
Yeah - facing the same issue on my end.

**Comment by ciregbulem** [comment]
@Chuckv01 I had to sign into the developer account Apple ID on the phone that received the 2FA verification code in order to fix this.

**Comment by mahlon-gumbs** [comment]
> @Chuckv01 I had to sign into the developer account Apple ID on the phone that received the 2FA verification code in order to fix this.

@ciregbulem did you have to do anything special when you logged into the account? Also, did you mean you logged into the developer account (as in developer.apple.com) or the Apple ID for the account (as in appleid.apple.com)?

Facing the same issue and simply logging in doesn't seem to resolve it for me, unfortunately.

**Comment by ciregbulem** [comment]
> > @Chuckv01 I had to sign into the developer account Apple ID on the phone that received the 2FA verification code in order to fix this.
> 
> @ciregbulem did you have to do anything special when you logged into the account? Also, did you mean you logged into the developer account (as in developer.apple.com) or the Apple ID for the account (as in appleid.apple.com)?
> 
> Facing the same issue and simply logging in doesn't seem to resolve it for me, unfortunately.

I think I installed one app (not sure if this step is needed) but that was it. To clarify, I logged into the Apple ID of the developer account on the phone (Settings > Apple Account) that is configured to receive the 2FA verification code. So if you have a different personal Apple ID than the one used for the developer account you'll need to sign out of the personal Apple ID on your phone and sign in to the developer account Apple ID. That fixed it for me.

**Comment by mahlon-gumbs** [comment]
Thanks @ciregbulem.
