### ISSUE TITLE
Uncheck Demo account checkbox in iTunesConnect

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#4241]
### New Issue Checklist

- [x] Updated deliver to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The submission process failed with this error `Enter a demo account user name and password`, but my app doesn't need demo account. Does `deliver` support in uncheck demo account checkbox?

Stack trace:
```
INFO [2016-04-17 19:21:56.53]: Submitting the app for review...
.../gems/spaceship-0.25.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	Enter a demo account user name and password. Enter a demo account user name and password.
.../gems/spaceship-0.25.1/lib/spaceship/tunes/tunes_client.rb:686:in `prepare_app_submissions'
.../gems/spaceship-0.25.1/lib/spaceship/tunes/app_submission.rb:117:in `create'
.../gems/spaceship-0.25.1/lib/spaceship/tunes/application.rb:288:in `create_submission'
.../gems/deliver-1.11.0/lib/deliver/submit_for_review.rb:8:in `submit!'
.../gems/deliver-1.11.0/lib/deliver/runner.rb:87:in `submit_for_review'
.../gems/deliver-1.11.0/lib/deliver/runner.rb:30:in `run'
.../gems/deliver-1.11.0/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
.../gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
.../gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
.../gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
.../gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
.../gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
.../gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
.../gems/deliver-1.11.0/lib/deliver/commands_generator.rb:132:in `run'
.../gems/deliver-1.11.0/lib/deliver/commands_generator.rb:12:in `start'
.../gems/deliver-1.11.0/bin/deliver:5:in `<top (required)>'
.../bin/deliver:23:in `load'
.../bin/deliver:23:in `<main>'
```

**Comment by luisherranz** [comment]
I was **about** to open the very same issue, how great is that :)

To illustrate it a bit further, the apps won't get submitted and if you login manually to iTunes connect this is the reason:
![screen shot 2016-04-14 at 12 48 08](https://cloud.githubusercontent.com/assets/3305402/14603704/91e3637a-056f-11e6-836e-df2da5131fc2.png)

**Comment by KrauseFx** [comment]
It seems like this affects every user trying to ship an app with `deliver`, right? I'll take a look into this

**Comment by lacostej** [comment]
@KrauseFx I had the same problem the other day so I unchecked the demo account (it comes checked by default)

**Comment by gran33** [comment]
@lacostej How could u uncheck the demo account via `deliver` or `fastlane`? (manually doesn't count)

**Comment by KrauseFx** [comment]
@gran33 Haha, working on it 😉

**Comment by luisherranz** [comment]
@KrauseFx In our case this happens when we want to add the contact information but don't add a demo account. For example:
```ruby
app_review_information(
  first_name: "John",
  last_name: "Smith",
  phone_number: "+555555555",
  email_address: "some@email.com",
)
```

**Comment by KrauseFx** [comment]
Thanks everyone, already in the middle of writing some code 🚀 I'll keep you up to date

**Comment by lyptt** [comment]
This seems to also occur with `pilot` just after logging "Distributing new build to testers"

**Comment by KrauseFx** [comment]
PR is live, waiting for the build and a PR review https://github.com/fastlane/fastlane/pull/4245 🎉

**Comment by hjanuschka** [comment]
in my case the PR does not fix the error

**Comment by KrauseFx** [comment]
@hjanuschka Could you share more information? In particular: is the checkbox currently enabled or disabled? Do you have a demo user and/or password

**Comment by carlosefonseca** [comment]
@KrauseFx How about the fields on the iTunes Connect's Build page? These are annoying because somehow I HAVE to put something in there. The checkbox on the AppStore tab is unchecked. Can't find a way to use Spaceship to set those fields 😕.

![screen shot 2016-04-18 at 19 03 11](https://cloud.githubusercontent.com/assets/14120/14614356/c4570cf2-0598-11e6-91f8-2341cc25a9b8.png)

**Comment by carlosefonseca** [comment]
@KrauseFx If I do this…

```ruby
app = Spaceship::Tunes::Application.find(params[:app_identifier])

build = app.builds.sort_by {|app| app.upload_date}.last
build.update_build_information!(whats_new: params[:whats_new])
```

I end up with this
```
Spaceship::TunesClient::ITunesConnectError: A demo account user name is required. A demo account password is required. A demo account user name is required. A demo account password is required.
from /Users/carlos/.gems/gems/spaceship-0.25.1/lib/spaceship/tunes/tunes_client.rb:174:in `handle_itc_response'
```

**Comment by lacostej** [comment]
@carlosefonseca the fix will be in 0.26 I think not 0.25.1 which you appear to be running.

if have you checked if the field on the App Front page is checked or not ?

![screen shot 2016-04-18 at 20 28 48](https://cloud.githubusercontent.com/assets/24282/14615061/42f19ae0-05a4-11e6-95e9-6db2af2d9989.png)

**Comment by carlosefonseca** [comment]
@lacostej I said on my first comment "The checkbox on the AppStore tab is unchecked." 🙂
Although that version isn't yet live. Maybe that makes some difference…
But I have apps just for testing that will never be live, so I kind of need a way to set the Demo Account for the uploaded build via Spaceship… (until Apple notices they messed up those builds)

**Comment by lacostej** [comment]
@carlosefonseca 

I looked at the code on Apple's side and here's what I see
````json
		"reviewUserName": {
			"value": "",
			"isEditable": true,
			"isRequired": false,
			"errorKeys": null,
			"maxLength": 400,
			"minLength": 1
		},
		"reviewPassword": {
			"value": "",
			"isEditable": true,
			"isRequired": false,
			"errorKeys": null,
			"maxLength": 400,
			"minLength": 1
		},
		"reviewAccountRequired": {
			"value": true,
			"isEditable": true,
			"isRequired": false,
			"errorKeys": null
		}
````

````html
<div class="fieldrow" ng-show="testinfo.data.reviewUserName.isEditable || testinfo.data.reviewPassword.isEditable">
                        <div class="halfcolumn mini">
                            <span class="inputWrapper">
                                <input type="text" placeholder="User name" ng-model="testinfo.data.reviewUserName.value" ng-required="testinfo.data.reviewUserName.isRequired" itc-field-server-error="testinfo.data.reviewUserName.errorKeys" itc-field-orig-val="originaltestinfo.data.reviewUserName.value" itc-field-cur-val="testinfo.data.reviewUserName.value" itc-field-pop-up-errors="true" maxlength="100" class="ng-isolate-scope ng-pristine ng-valid ng-valid-required">
                                <span class="errorPopUp mainError ng-binding" ng-hide="testinfo.data.reviewUserName.errorKeys.length > 0">
                                    This field is required.
                                </span>
                                <span class="errorPopUp srvError ng-hide" ng-show="testinfo.data.reviewUserName.errorKeys.length > 0">
                                    <!-- ngRepeat: msg in testinfo.data.reviewUserName.errorKeys -->
                                </span>
                            </span>
                        </div>
                        <div class="halfcolumn mini">
                            <span class="inputWrapper">
                                <input type="text" placeholder="Password" ng-model="testinfo.data.reviewPassword.value" ng-required="testinfo.data.reviewPassword.isRequired" itc-field-server-error="testinfo.data.reviewPassword.errorKeys" itc-field-orig-val="originaltestinfo.data.reviewPassword.value" itc-field-cur-val="testinfo.data.reviewPassword.value" itc-field-pop-up-errors="true" maxlength="100" class="ng-isolate-scope ng-pristine ng-valid ng-valid-required">
                                <span class="errorPopUp mainError ng-binding">
                                    This field is required.
                                </span>
                                <span class="errorPopUp srvError">
                                    <!-- ngRepeat: msg in testinfo.data.reviewPassword.errorKeys -->
                                </span>
                            </span>
                        </div>
                    </div>
````

So I am sending #4250 as tentative to work around Apple server side issue.

**Comment by gran33** [comment]
@carlosefonseca U can simply submit the app using the `deliver` flags, in your case 
`--skip_binary_upload` Skip uploading an ipa or pkg to iTunes Connect
Anyway u can see all flags, just type `deliver -h`

**Comment by carlosefonseca** [comment]
@lacostej Thank you! Seems about right. Will try to test it! I did look into the raw_data but I didn't figure out how to apply the modifications.

**Comment by KrauseFx** [comment]
New release is live https://github.com/fastlane/spaceship/releases/tag/0.26.0. Let us know how that works for you

**Comment by carlosefonseca** [comment]
Expanded @lacostej's fix to also work on `update_build_information`.

**Comment by KrauseFx** [comment]
Thanks to @carlosefonseca I just pushed https://github.com/fastlane/spaceship/releases/tag/0.26.1, could you update and give it a try? 👍

**Comment by gran33** [comment]
Just to make it clear, I use `deliver` and Not `spaceship` directly.
The default demo account is uncheck or check? 

As far as I checked (using `deliver` latest version (`1.11.1`) which uses the latest `spaceship` version `0.26.1`) the error still occur. **Do I need to change the way I use `deliver`?**

I use `deliver` like this:
`bundle exec deliver --skip_binary_upload --skip_screenshots --skip_metadata --force --submit_for_review --automatic_release --verbose`

With this `Deliverfile`:
```
###################### App Metadata ######################
app_identifier "com.app.bundle.id"
automatic_release true

submission_information({
    export_compliance_encryption_updated: false,
    export_compliance_is_exempt: false,
    export_compliance_uses_encryption: false,
    export_compliance_contains_proprietary_cryptography: false,
    export_compliance_contains_third_party_cryptography: false,
    content_rights_contains_third_party_content: false,
    content_rights_has_rights: false,
    add_id_info_uses_idfa: false,
    add_id_info_serves_ads: false,
    add_id_info_limits_tracking: false,
    add_id_info_tracks_action: false,
    add_id_info_tracks_install: false
})
app_review_information(
  first_name: "my name",
  last_name: "my last name",
  phone_number: "+1 1231231231",
  email_address: "example@mail.com",
  notes: ""
)
```

**Comment by carlosefonseca** [comment]
@gran33 Yeah, it seems `deliver` isn't yet aware of the checkbox. Check PR #4281.

**Comment by iPavel92** [comment]
I've checked the @carlosefonseca patch, it isn't working for me.
Steps I've done:
1. updated to lastest deliver (1.11.1) and spaceship (0.26.1)
2. uninstalled old versions of deliver and spaceship via "gem cleanup"
3. locally patched upload_metadata.rb like [this](https://github.com/fastlane/fastlane/pull/4281/files)
Tried with different configs:
```
app_review_information(
  first_name: "my name",
  last_name: "my last name",
  phone_number: "+1 1231231231",
  email_address: "example@mail.com",
  notes: "bla bla"
)
```
and
```
app_review_information(
  first_name: "my name",
  last_name: "my last name",
  phone_number: "+1 1231231231",
  email_address: "example@mail.com",
  demo_user: "",
  demo_password: "",
  notes: "bla bla"
)
```
Still getting

```
[!] The request could not be completed because:
Enter a demo account user name and password. Enter a demo account user name and password
```

**Comment by KrauseFx** [comment]
I just pushed a new release, could you try https://github.com/fastlane/deliver/releases/tag/1.11.2

**Comment by iPavel92** [comment]
Having the same error on 1.11.2

**Comment by gran33** [comment]
I m with @iPavel92, Same demo account error

**Comment by fwal** [comment]
Just out of curiosity and clarification: have anyone tried setting demo_user and demo_password to non-empty strings?

**Comment by TKBurner** [comment]
@iPavel92 Thanks for following up. Have you tried entering a non-empty string as suggested above? We are still going to look into this. Thanks!

**Comment by gran33** [comment]
@TKBurner and @fwal I entered this:
```
app_review_information(
  first_name: "my name",
  last_name: "my last name",
  phone_number: "+1 1231231231",
  email_address: "example@mail.com",
  notes: ""
)
```

**Comment by iPavel92** [comment]
@fwal never tried. It wouldn't help because of this condition: https://github.com/fastlane/fastlane/pull/4266
`build_info['reviewAccountRequired']['value'] = ((review_user_name || "").to_s + (review_password || "").to_s).length > 0`

**Comment by gran33** [comment]
If I add `--skip_metadata` flag, the review information skip to? I suspect it skip both.

**Comment by kaomte** [comment]
Yes, I'm in the same boat as @iPavel92.

Getting this error. I don't have demo_user or demo_password set in app_review_information.  On deliver 1.11.2.
```
  [!] The request could not be completed because:
	Enter a demo account user name and password. Enter a demo account user name and password.
```

**Comment by TKBurner** [comment]
@kaomte Thanks for following up. We will have a look and update on this thread. Thanks!

**Comment by kaomte** [comment]
@TKBurner I finally got things working on my end. I misunderstood how the fix worked. I was thinking that during the app submission that deliver would uncheck the box. Now I realize the the box is checked/unchecked when the build information is updated, not during submission. I had updated build information with an older version of deliver and after the fix was submitting with the latest version of deliver and still getting the same error. 

Now, after updating the build information with the latest deliver, submission works fine.

**Comment by KrauseFx** [comment]
Yeah great to hear @kaomte 👍

**Comment by fulldecent** [comment]
@kaomte @gran33 @iPavel92 could you please share the final, working Deliverfile that you are using which allows unattended delivery?

**Comment by evilDave** [comment]
This issue is closed but I am still getting this issue. Is there a way to have deliver uncheck that box or do we have to put in some kind of dummy info for user and pass?
Our app does not need a test user, so normally we uncheck the box and leave it at that. How does this work with deliver?

**Comment by TKBurner** [comment]
@evilDave Thanks for following up. You need to update your build information for the app first, and then the box should be unchecked by default. Thanks!

**Comment by evilDave** [comment]
Excellent, that is it. It seems like if you create an app version manually, this checkbox gets checked by default now. Also if you create a version with deliver and let it keep the defaults for build information, this box will also be checked.
I now have deliver set up to create new versions for me so as long as I specify, as you say, the app_review_information then the box will be unchecked.
Thanks!

**Comment by ConfusedVorlon** [comment]
@fulldecent this works for me to fix the demo account issue

```
app_review_information(
  first_name: "Rob",
  last_name: "MY_NAME",
  phone_number: "MY_NUMBER",
  email_address: "MY_EMAIL",
  demo_user: "",
  demo_password: "",
  notes: ""
)
```

**Comment by simme** [comment]
@ConfusedVorlon:
I'm having some issues figuring out where this fits in my Fastfile. I'm using Pilot, not deliver

**Comment by ConfusedVorlon** [comment]
I keep that in my deliverfile. I'm not familiar with pilot - but worth trying the deliverfile to see if it uses the same source.

**Comment by TKBurner** [comment]
@simme Did you have a chance to give this a test? You might need to run both commands to get the outcome you are looking for. Hope you have a wonderful day! 👍

**Comment by evilDave** [comment]
Is this info used by pilot? I don't think I have seen any such checkbox when adding a build to testflight.

**Comment by simme** [comment]
I put the stuff that ConfusedVorlon posted into a Deliverfile (modified for my needs obviously). Didn't work.

There's a checkbox when pushing a build out to external testers.

**Comment by TKBurner** [comment]
@simme Can you share you full input and output? First run sudo gem update fastlane. Thanks!

**Comment by owurman** [comment]
I'm just starting up with Pilot so I might be doing something wrong, but I'm also still hitting this. I uncheck the Demo Account checkbox it explicitly in my uploaded (and approved) TestFlight builds, but when creating the next one with Pilot, the checkbox is always there.
`fastlane actions pilot`
doesn't indicate there's any way of setting this, or of passing app_review_information via the equivalent of a Deliverfile?

**Comment by evilDave** [comment]
I too have just pushed a build to TestFlight and the checkbox has become checked. I do have the entries in the deliverfile that prevent the box from being checked by deliver.

**Comment by TKBurner** [comment]
@evilDave Thanks for reaching out. Does this occur every time and on multiple apps? Thanks!

**Comment by owurman** [comment]
@TKBurner Is it expected that pilot will pick up the app_review_information from the Deliverfile?

**Comment by owurman** [comment]
To answer my own question after looking at the code, it seems that pilot does **not** read in the Deliverfile. So where exactly are we supposed to set the demo account info assuming we actually have one? Perhaps there needs to be a Pilotfile?

**Comment by evilDave** [comment]
@TKBurner yes it's happening on a few projects. I do believe that I've found that once you go into iTunes connect and manually uncheck the box, new builds have it unchecked.
I second the notion that what we probably need is a pilotfile with the appropriate section in it.

**Comment by TKBurner** [comment]
@evilDave I've marked this with a few more flags to see if anyone is interested in implementing this. Thanks for working with us!

**Comment by owurman** [comment]
I'm planning on doing a pull request to add a Pilotfile (or to read the Deliverfile... not sure which makes more sense), but to be honest I'm terrified of breaking my current fastlane setup when checking out a fork instead.

**Comment by evilDave** [comment]
Let me know where you are doing this and I will check it out of your repo and try it out. As for which file, I would suggest Pilotfile.

**Comment by owurman** [comment]
The reason I have against a separate Pilotfile is that the app_review_information is mostly likely identical to the one you'd use for deliver. I think it makes more sense to add any pilot-specific deliverable fields to the Deliverfile. I suppose both could source some other common file, though.

**Comment by evilDave** [comment]
What would you do if the app_review_information was not the same for the testflight build and the production release? This could easily be true for anyone that _does_ need a demo user login.

Once could presumably use the tools separately also... The fact that for one tool, pilot, the settings file is called Deliverfile might be a point of confusion.

**Comment by owurman** [comment]
Yeah, you're right. I'll make it Pilotfile, and anyone with commonality between the two will just have to source a third file.
