### ISSUE TITLE
snapshot reset_simulators returns error code 157 and 159

### ISSUE THREAD

**Issue by 5amfung** [fastlane/fastlane#4768]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

snapshot reset_simulators returns error code 157 and 159.

I've seen similar older issues resolved by updating to latest version snapshot, but I'm running the latest version now and the issue seems to resurface again.

##### Complete output when running fastlane, including the stack trace and command used

```
$ snapshot reset_simulators
Are you sure? All your simulators will be DELETED and new ones will be created! (y/n)
y
Removing device iPhone 4s (3F59B9F7-86E3-44B8-93D9-DFD9DD9B600E)
Removing device iPhone 5 (E75C555C-B71E-441B-8361-29CB33B65C4F)
Removing device iPhone 5s (4ECC5072-A3F4-4EA8-BDF8-20946D08D65D)
Removing device iPhone 6 (3D56B26C-1A74-4B75-B38E-710C6A4B4D1E)
Removing device iPhone 6 Plus (89A71F49-FD54-415C-97C9-6E0198D680BD)
Removing device iPhone 6s (79CBD03D-38D0-4F0F-9882-83BC6439F66A)
Removing device iPhone 6s Plus (F577905F-09AE-49B3-BE53-B54B086B1E3A)
Removing device iPad 2 (811BBF47-E588-4913-BAE6-9864DF181C1F)
Removing device iPad Retina (99C08E88-9082-4EDB-8EC7-FE9F72A437DF)
Removing device iPad Air (B475C285-9FC3-4E51-9EE3-442DF64135F5)
Removing device iPad Air 2 (07B8BD87-F3FF-4F4F-8C73-73643D0A3B87)
Removing device iPad Pro (2053637A-B35D-40E2-8D1E-0232F6B6B617)
Removing device 38mm (F49181D9-2421-4871-8C8B-A9FCE2698A66)
Removing device 42mm (2340788C-1C6A-4DEF-9556-EF52ECEDA16E)
Removing device 42mm (6B33E469-5047-4C86-89EE-B1FE99BE5748)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Creating ["iPhone 4s", "com.apple.CoreSimulator.SimDeviceType.iPhone-4s"] for iOS version 9.3
Creating ["iPhone 5", "com.apple.CoreSimulator.SimDeviceType.iPhone-5"] for iOS version 9.3
Creating ["iPhone 5s", "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"] for iOS version 9.3
Creating ["iPhone 6", "com.apple.CoreSimulator.SimDeviceType.iPhone-6"] for iOS version 9.3
Creating ["iPhone 6 Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus"] for iOS version 9.3
Creating ["iPhone 6s", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"] for iOS version 9.3
Creating ["iPhone 6s Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus"] for iOS version 9.3
Creating ["iPad 2", "com.apple.CoreSimulator.SimDeviceType.iPad-2"] for iOS version 9.3
Creating ["iPad Retina", "com.apple.CoreSimulator.SimDeviceType.iPad-Retina"] for iOS version 9.3
Creating ["iPad Air", "com.apple.CoreSimulator.SimDeviceType.iPad-Air"] for iOS version 9.3
Creating ["iPad Air 2", "com.apple.CoreSimulator.SimDeviceType.iPad-Air-2"] for iOS version 9.3
Creating ["iPad Pro", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro"] for iOS version 9.3
Creating ["Apple TV 1080p", "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p"] for tvOS version 9.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=157):
Incompatible device
Creating ["Apple Watch - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"] for watchOS version 2.2
Creating ["Apple Watch - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"] for watchOS version 2.2
Creating device pair of 9FC7A36D-D96E-4FA5-A4FB-B2FDB99E8213 and 6B33E469-5047-4C86-89EE-B1FE99BE5748
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=157):
The operation couldn’t be completed. Invalid argument
Invalid argument
```

### Configuration Files

Snapfile:
```ruby
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5"
])
languages([
  "en-US"
])
output_directory "./fastlane/screenshots"
scheme "Example"
workspace "./Example.xcworkspace"
```

### Environment

Xcode version: Version 7.3.1 (7D1014)
fastlane version (run `fastlane -v`): fastlane 1.89.0
snapshot version: snapshot 1.12.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by vpolouchkine** [comment]
I'm seeing these errors, thanks for the report; we'll take a look.

**Comment by mfurtak** [comment]
Please see: https://github.com/fastlane/fastlane/issues/4423#issuecomment-221363437 for an explanation of why this is happening.

You may be able to work around the problem in the short term if you are able to 

`xcrun simctl erase [ID]`

and then

`xcrun simctl delete [ID]`

the simulator that is stuck in a bad state. If you are in the same position that I was, please note that [because of an Apple bug](https://forums.developer.apple.com/thread/28571), you may have to download a the missing watch OS version that the simulator depends on before `erase` and `delete` will work 😞 

I've merged https://github.com/fastlane/fastlane/pull/4834 to fix the problem more permanently, and that will go out in the next release! 🚀

**Comment by esetnik** [comment]
I've updated to snapshot `1.12.3` and i'm still seeing the behavior.

> you may have to download the missing watch OS version that the simulator depends on before erase and delete will work 😞

how do I go about verifying that I have the correct watchOS versions installed?

```
> snapshot -v
snapshot 1.12.3
> snapshot reset_simulators
Are you sure? All your simulators will be DELETED and new ones will be created! (y/n)
y
Removing device iPhone 4s (D67F4359-5887-4E3D-9305-B77778239777)
Removing device iPhone 5 (76E8614F-8818-4649-B80D-0C9D4D124C0C)
Removing device iPhone 5s (C96B0BA1-C72A-45C0-8AB9-7B0A6BEA4038)
Removing device iPhone 6 (521AA00E-B46B-4635-B332-AB88F8524B8F)
Removing device iPhone 6s (7A67F2D1-7120-42C3-951F-237B1B745E01)
Removing device iPhone 6s Plus (369A6276-AB78-4D66-8BC8-DFE119F10C37)
Removing device iPad 2 (E05D259B-7F60-4116-AE1F-332D3A9BCBB4)
Removing device iPad Retina (6E1D30B2-07BB-402F-BBF2-617EB2DC5FB1)
Removing device iPad Air (0EF3FA1A-C2EB-4BE7-A103-20B845361854)
Removing device iPad Air 2 (785312C6-10C1-4B5D-BC42-A9D2379FDC6A)
Removing device iPad Pro (03B7F0B5-A0BF-4748-9BF8-ADA96F2C4349)
Removing device Apple TV 1080p (11D4D1F6-5F20-4909-84FF-B40D71BB04C7)
Removing device Apple Watch - 38mm (44ADD723-09EC-4712-88B3-4F0C8085F2A0)
Removing device Apple Watch - 38mm (A466987E-04F3-4C46-AABF-CF8986E7E729)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Removing device Apple Watch - 42mm (7E0CDBDA-19D6-4C89-B68B-42C32FBF5D5E)
Removing device Apple Watch - 42mm (07E2DBDA-70A3-4693-8CFE-0E0989D13068)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Removing device Apple Watch - 38mm (0AA6BAEB-6EF9-4D13-8F5A-660BDDB5E24C)
Removing device Apple Watch - 42mm (16C9A896-7DC9-46F7-A75C-833AB8BADB3B)
Removing device Apple Watch - 42mm (56B8A29C-387B-49CC-B1AE-CAB7FF433C0D)
Removing device Apple Watch - 38mm (CBF25CDD-2492-444C-B7C2-3AE6EDC50E4F)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Removing device Apple Watch - 38mm (D8D739AE-FFFB-4E6E-ACD9-E69B9CA9E3F1)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Removing device Apple Watch - 42mm (3A5DC1E1-594A-41BD-9C1C-37FB388F8F9D)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Removing device Apple Watch - 42mm (6621F801-8CFB-4817-8144-61AAA89A3E6E)
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
Unable to delete device in current state: Creating
Creating ["iPhone 4s", "com.apple.CoreSimulator.SimDeviceType.iPhone-4s"] for iOS version 9.3
Creating ["iPhone 5", "com.apple.CoreSimulator.SimDeviceType.iPhone-5"] for iOS version 9.3
Creating ["iPhone 5s", "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"] for iOS version 9.3
Creating ["iPhone 6", "com.apple.CoreSimulator.SimDeviceType.iPhone-6"] for iOS version 9.3
Creating ["iPhone 6 Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus"] for iOS version 9.3
Creating ["iPhone 6s", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"] for iOS version 9.3
Creating ["iPhone 6s Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus"] for iOS version 9.3
Creating ["iPad 2", "com.apple.CoreSimulator.SimDeviceType.iPad-2"] for iOS version 9.3
Creating ["iPad Retina", "com.apple.CoreSimulator.SimDeviceType.iPad-Retina"] for iOS version 9.3
Creating ["iPad Air", "com.apple.CoreSimulator.SimDeviceType.iPad-Air"] for iOS version 9.3
Creating ["iPad Air 2", "com.apple.CoreSimulator.SimDeviceType.iPad-Air-2"] for iOS version 9.3
Creating ["iPad Pro", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro"] for iOS version 9.3
Creating ["Apple TV 1080p", "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p"] for tvOS version 9.2
Creating ["Apple Watch - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"] for watchOS version 2.1
Creating ["Apple Watch - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"] for watchOS version 2.2
Creating ["Apple Watch - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"] for watchOS version 2.1
Creating ["Apple Watch - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"] for watchOS version 2.2
Creating device pair of 2BD597CA-DCA7-4B16-B1D3-6FFFA6DFA435 and 56B0CA1B-8B24-4226-B8E1-4AAC23CC2E90
```

**Comment by mfurtak** [comment]
Hi @esetnik  👋 

Heh, so, the part that is fixed is the very last line there:

```
Creating device pair of 2BD597CA-DCA7-4B16-B1D3-6FFFA6DFA435 and 56B0CA1B-8B24-4226-B8E1-4AAC23CC2E90
```

Before the fix that would have failed to create a watch-phone pair for you. 😊 

The simulators which are stuck in a bad state have to be dealt with manually, unfortunately. Here's how you can do that:

Run `xcrun simctl list devices` and look for entries at the bottom like these:

```
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 38mm (22C04589-2AD4-42BB-9869-FB2331708E62) (Creating) (unavailable, runtime profile not found)
    Apple Watch - 42mm (B98D4701-C719-41CD-BCCD-1288464D9B26) (Creating) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-1 --
    Apple Watch - 38mm (AF341B69-678E-48B0-9D12-A7502662D1BE) (Creating) (unavailable, runtime profile not found)
    Apple Watch - 42mm (D2C4CBD0-DF62-45E3-8E25-72201827482E) (Creating) (unavailable, runtime profile not found)
```

My output there is telling me that I don't currently have watch OS 2.0 or 2.1 installed. I have to install them to be able to delete those broken simulators 😫  You can do that through the Xcode Preferences > Components tab:

![screen shot 2016-05-25 at 5 55 19 pm](https://cloud.githubusercontent.com/assets/343134/15557554/ec2ec94c-22a1-11e6-900f-e60e2741cc60.png)

Once any missing sim runtime OS images are installed, for each simulator in a bad state, run:

```
xcrun simctl erase [ID] && xcrun simctl delete [ID]
```

where an example ID for me was `22C04589-2AD4-42BB-9869-FB2331708E62`

That should get your simulator list cleaned up, and then future `reset_simulators` should be OK!

**Comment by 5amfung** [comment]
Thanks @mfurtak for the instructions.  Everything just worked now.  I hope others who ran into similar would find this post useful.
