### ISSUE TITLE
Keychain prompts for permission to use private key regardless of access control settings on sierra

### ISSUE THREAD

**Issue by godrei** [fastlane/fastlane#6866]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlan gym hangs on `xcodebuild archive` commands.

Keychain prompts for permission to use private key regardless of access control settings on sierra this cases a hang on build servers when tools calling `codesign` tool, like signing an archive, or during copying a framework or embedding pods.

Related [openradar issue](https://openradar.appspot.com/28524119).

The mentioned solution seems to be working, our implementation: https://github.com/bitrise-io/steps-certificate-and-profile-installer/blob/master/main.go#L548

# Log 1:

```
+----------------------+-------------------------+
|             [32mSummary for gym 1.11.3[0m             |
+----------------------+-------------------------+
| scheme               | [REDACTED]                 |
| configuration        | Alpha                   |
| use_legacy_build_api | true                    |
| export_method        | development             |
| workspace            | ./[REDACTED].xcworkspace   |
| destination          | generic/platform=iOS    |
| output_name          | [REDACTED]                 |
| clean                | false                   |
| output_directory     | .                       |
| silent               | false                   |
| buildlog_path        | ~/Library/Logs/gym      |
| xcode_path           | /Applications/Xcode.app |
+----------------------+-------------------------+

[07:58:19]: [4m[36m$ set -o pipefail && xcodebuild -workspace ./[REDACTED].xcworkspace -scheme [REDACTED] -configuration 'Alpha' -destination 'generic/platform=iOS' -archivePath /Users/vagrant/Library/Developer/Xcode/Archives/2016-11-03/[REDACTED]\ 2016-11-03\ 07.58.19.xcarchive archive | tee /Users/vagrant/Library/Logs/gym/[REDACTED]-[REDACTED].log | xcpretty[0m[0m
[07:58:24]: [35m[33m▸[0m [39;1mBuilding[0m [REDACTED]/[REDACTED]-notification [(Release)][0m
[07:58:24]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
[07:58:24]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
[07:58:24]: [35m[33m▸[0m [39;1mCompiling[0m NotificationService.swift[0m
[07:58:29]: [35m[33m▸[0m [39;1mCompiling[0m NotificationService.swift[0m
[07:58:37]: [35m[33m▸[0m [39;1mLinking[0m [REDACTED]-notification[0m
[07:58:38]: [35m[33m▸[0m [39;1mLinking[0m [REDACTED]-notification[0m
[07:58:43]: [35m[33m▸[0m [39;1mGenerating '[REDACTED]-notification.appex.dSYM'[0m[0m
[07:58:45]: [35m[33m▸[0m [39;1mTouching[0m [REDACTED]-notification.appex[0m
[07:58:45]: [35m[33m▸[0m [39;1mSigning[0m /Users/vagrant/Library/Developer/Xcode/DerivedData/[REDACTED]-euwzwswygybbklfshqvjvmmgzspa/Build/Intermediates/ArchiveIntermediates/[REDACTED]/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/[REDACTED]-notification.appex[0m

hang on this line...
```

# Log 2:

```
+----------------------+-------------------------+ 
| Summary for gym 1.11.3 | 
+----------------------+-------------------------+ 
| scheme | Palace | 
| configuration | Adhoc | 
| use_legacy_build_api | true | 
| export_method | ad-hoc | 
| project | ./[REDACTED].xcodeproj | 
| destination | generic/platform=iOS | 
| output_name | [REDACTED] | 
| clean | false | 
| output_directory | . | 
| silent | false | 
| buildlog_path | ~/Library/Logs/gym | 
| xcode_path | /Applications/Xcode.app | 
+----------------------+-------------------------+

[12:13:35]: $ set -o pipefail && xcodebuild -scheme [REDACTED] -project ./[REDACTED].xcodeproj -configuration 'Adhoc' -destination 'generic/platform=iOS' -archivePath /Users/vagrant/Library/Developer/Xcode/Archives/2016-11-03/[REDACTED]\ 2016-11-03\ 12.13.35.xcarchive archive | tee /Users/vagrant/Library/Logs/gym/[REDACTED]-[REDACTED].log | xcpretty 
[12:13:37]: ▸ Building [REDACTED]/[REDACTED] [Adhoc] 
[12:13:37]: ▸ Check Dependencies 
[12:14:36]: ▸ Compiling [REDACTED]_vers.c 
[12:14:37]: ▸ Compiling [REDACTED]_vers.c 
[12:14:37]: ▸ Linking [REDACTED] 
[12:14:39]: ▸ Linking [REDACTED] 
[12:14:39]: ▸ Compiling LaunchScreen.storyboard 
[12:14:45]: ▸ Processing Info.plist 
[12:14:45]: ▸ Generating '[REDACTED].app.dSYM' 
[12:14:45]: ▸ Running script 'Copy Frameworks'

hang on this line...
```

# Log 3:

```
Compiling alot...

[20:42:44]: ▸ Compiling Main.storyboard
[20:42:50]: ▸ Processing Info.plist
[20:42:50]: ▸ Generating '[REDACTED].app.dSYM'
[20:42:50]: ▸ Running script 'Run Script'
[20:42:50]: ▸ Running script '[CP] Embed Pods Frameworks'

hang on this line...
```

**Comment by godrei** [comment]
All of these builds was working fine before sierra, all of these builds are failing on the same part of `xcodebuild archive` calls (when it uses `codesign`).

Based on the openradar issue i mentioned previously and on our tests, it seems without calling `security set-key-partition-list ...` you can not avoid to keychain prompt for permission (on sierra), even if you installed the certificate correctly and opened the keychain with `security` command calls.

Am i missing something?

**Comment by kwoylie** [comment]
I'm having the exact same issue too

**Comment by viktorbenei** [comment]
Practically this issue means that fastlane hangs at any point which requires code signing, on a clean macOS Sierra, in a non interactive environment (CI),  because of the permission popup.

**Comment by KrauseFx** [comment]
Is this something that was recently introduce by _fastlane_? Did it work before?

**Comment by viktorbenei** [comment]
This is a change in macOS Sierra - the same fastlane build works on El Capitan, but "hangs" on Sierra, waiting for the user to click the "Allow" popup for code signing. See the related radar: https://openradar.appspot.com/28524119

**Comment by viktorbenei** [comment]
To highlight, the solution we found is to do this: https://github.com/bitrise-io/steps-certificate-and-profile-installer/blob/master/main.go#L569 - `"security", "set-key-partition-list", "-S", "apple-tool:,apple:", "-k", configs.KeychainPassword, configs.KeychainPath`, after `"security", "import", cert, "-k", configs.KeychainPath, "-P", pass, "-A"`

Have to be done only on Sierra, this command would fail on El Capitan.

**Comment by TKBurner** [comment]
@viktorbenei Thanks for working with us on this. I've circled back with the core team to see what we can do to improve this 👍

**Comment by viktorbenei** [comment]
Thanks @TKBurner , let us know if we can help with anything else!

**Comment by milch** [comment]
I'll investigate possible fixes now, expect a PR soon 👍

**Comment by viktorbenei** [comment]
Awesome news, thank you @milch !

**Comment by milch** [comment]
This is now done, once the PRs are merged we'll release versions of the fastlane tools where this is fixed 🚀

**Comment by viktorbenei** [comment]
Awesome news, thank you! 🎉

**Comment by KrauseFx** [comment]
Thanks @viktorbenei and @godrei for providing all this information, it was super helpful 👍

**Comment by kylejm** [comment]
Hey all, thanks for the hard work on this!

I'm still experiencing this problem after upgrading `gym` to 1.12.0 and `match` to 0.11.0.

My logs are basically the same as Log 2 and Log 3 above.

Running on Bitrise with Xcode 8.1 on macOS 10.12 (Sierra).

Anything I could be missing or not updated? All the rest of our fastlane gems are up to date too.

**Comment by milch** [comment]
What's your `fastlane_core` version? 

Also `match` needs to have re-downloaded the certificates at least once for it to work, so try removing the certs manually and re-running `match`

**Comment by kylejm** [comment]
fastlane_core is at 0.55.0. 

I'm running on CI and the cheers are re-downloaded by `match` on every build.

**Comment by kylejm** [comment]
Can this one be re-opened please? It's quite a blocker for us, stopping any submissions on CI via `fastlane`. 😢

**Comment by milch** [comment]
Did you provide the `keychain_password` param to `match`?

**Comment by kylejm** [comment]
No, but I didn't think you'd have to if the item was added by `match`? I don't know what the password would be for keychain on our CI if I were to have to do this. Maybe @godrei or @viktorbenei can advise if it comes to that.

**Comment by milch** [comment]
@kylejm The keychain password is (unfortunately) required by the `set-key-partition-list` command, even if the keychain is already unlocked. Usually for the (default) login keychain the password is the user's account password. 

As a workaround, you could create a temporary keychain with a known password and use that to import your certificates. The only thing you'd have to take care of is creating the keychain and pointing match to your keychain with the `keychain_name` param (and also setting `keychain_password`, of course).

**Comment by mono0926** [comment]
@milch 

Thanks, the problem resolved 👍 
I was troubled by hangs as well as @kylejm yet, but it work again now 🎉 

## Bitrise:

Defined `MATCH_KEYCHAIN_NAME` and `MATCH_KEYCHAIN_PASSWORD`.

<img width="375" alt="screen shot 2016-11-15 at 8 26 51" src="https://cloud.githubusercontent.com/assets/1255062/20287071/a0193f16-ab0d-11e6-97f6-cd66b98af622.png">

## fastlane:

Defined this and call it before `match`

```ruby
private_lane :create_temporary_keychain do
	create_keychain(
	  name: ENV["MATCH_KEYCHAIN_NAME"], 
	  password: ENV["MATCH_KEYCHAIN_PASSWORD"],
	  timeout: 1200
	  )
end
```

**Comment by milch** [comment]
@mono0926 Thanks for posting your solution! 

@kylejm Let me know if that resolves it!

**Comment by mono0926** [comment]
I wrote the article (in Japanese, sorry).
[Bitrise Xcode 8.1などのSierra製CIマシンとfastlaneの組み合わせでビルドが出来ない問題が解決🎉 – Swift・iOSコラム – Medium](https://medium.com/swift-column/fastlane-bitrise-ef1125a1d89a#.4qayqhx1n)

**Comment by vincentsaluzzo** [comment]
Hello there,

I've trying all your solution but nothing works for me. 
My build on bitrise still block when running `carthage copy-frameworks` command in run script phase.
The fix was release in the fast lane 1.108 tool suite ?

**Comment by vincentsaluzzo** [comment]
Mmmh I write a bad character in bitrise environment variable sorry.

**Comment by milch** [comment]
@vincentsaluzzo So is it working for you now?

**Comment by kylejm** [comment]
I'm not quite sure why this solution of creating a new keychain needs to used when @viktorbenei gives a [solution that works without needing to do so](https://github.com/fastlane/fastlane/issues/6866#issuecomment-258889886). @milch could you clarify that for me, I think I'm missing something. :)

I'll try the solution given by @mono0926.

**Comment by milch** [comment]
@kylejm I'm guessing that since @viktorbenei is a cofounder of bitrise.io and posted code taken from the bitrise source, they can read the keychain password for the login keychain from their configuration.

**Comment by viktorbenei** [comment]
For reference, the login keychain password is `vagrant`, which can also be retrieved from the `$BITRISE_KEYCHAIN_PASSWORD` env var - you can use this env var as the match keychain password.

**Comment by milch** [comment]
Ah, thanks @viktorbenei! I'll close this, then.

**Comment by Sega-Zero** [comment]
@KrauseFx if I have only `KEYCHAIN_NAME` specified, shouldn't `match` read it if `MATCH_KEYCHAIN_NAME` is not specified?
Just faced this trouble on Travis CI, see [Travis CI issue](https://github.com/travis-ci/travis-ci/issues/6791#issuecomment-264895705). Shouldn't match call this itself, instead of making such a workarounds?

**Comment by viktorbenei** [comment]
An update from bitrise.io side - the `MATCH_KEYCHAIN_PASSWORD` env var is now defined on all macOS VMs by default, to the same value as `BITRISE_KEYCHAIN_PASSWORD` (see https://github.com/fastlane/fastlane/issues/6866#issuecomment-260791806 ).

**Comment by milch** [comment]
@Sega-Zero We usually only use the prefixed versions of environment variables, to avoid clashes with other tools and unintended side effects. Sometimes non-prefixed versions are available though for compatibility reasons, but there are currently efforts underway to remove those: #6659

If you want to use both, it's best if you just do `ENV["MATCH_KEYCHAIN_NAME"] = ENV["KEYCHAIN_NAME"]` at the beginning of your Fastfile.

**Comment by guidomb** [comment]
I experienced the same issue. Copy frameworks hangs (both in travisci and bitrise). In my case I was creating a new keychain in a before hook. That was working fine before migrating to Xcode 8. Any idea what could be the problem? I fixed the problem by using the default keychain provided by bitrise but I would like to create / destroy a new keychain. Is it possible?

Here is an example of how I was creating / destroying the keychain

```ruby
before_all do |lane|
    create_keychain(
      name: 'syrmo_keychain',
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: SecureRandom.base64
    )
end

error do |lane, exception|
  delete_keychain(name: 'syrmo_keychain')
end

after_all do |lane|
  delete_keychain(name: 'syrmo_keychain')
end
``` 

Is there a way to tell `gym` which keychain to use?

**Comment by milch** [comment]
@guidomb Which version of fastlane/gym are you using?

**Comment by guidomb** [comment]
@milch 2.14.2

**Comment by hborders** [comment]
Sorry for invading this issue, but this seems to be the only recent discussion I can find about `key-partition-list`s.

Is there any special requirements for getting https://github.com/fastlane/fastlane/issues/6866#issuecomment-258889886 to work?

I'm trying to stop security prompts when signing for a certificate I'm importing outside of fastlane (because I have a separate secrets data store I have to use).

Basically, I import the key into the login keychain the normal way:

```
security import "${PEM_FILE}" -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign -T /usr/bin/security
```

And then of course if I try to codesign something, I get prompted:

```
codesign --force --sign "${IDENTITY_HASH} `mktemp`
```

So, I tried setting the key partition list, but I just get a big dump of my keychain, and no affect if I try to run `codesign` again.

```
security set-key-partition-list -S apple-tool:,apple: -k "${PASSWORD}" ~/Library/Keychains/login.keychain
```
```
```

**Comment by hborders** [comment]
I figured out my problem. In my `import` command, I didn't supply a password. You must supply a password when importing or `set-key-partition-list` doesn't work. I outlined my problem on [stackoverflow](http://stackoverflow.com/a/43002580/9636). Sorry again for the invasion. Thanks for a great product!
