### ISSUE TITLE
Produce: You must choose a primary language. You must choose a primary language.

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#7074]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Run produce to create new app in ItunesConnect, it cannot create new app due to missing primary language although i already specific the language.
##### 
18:40:16]: [32m--- Step: produce ---[0m
[18:40:16]: [32m---------------------[0m

+----------------+----------------------------------+
|             [32mSummary for produce 1.3.0[0m             |
+----------------+----------------------------------+
| username       | developers@360.com         |
| app_name       | "CRUYFF"                         |
| team_id        | QWERTYUI                      |
| team_name      | " bv"         |
| app_identifier |ABC |
| language       | Dutch                            |
| app_version    | 2.11.0                           |
| sku            | ABC|
| company_name   | "bv"         |
| itc_team_id    | 12345678                        |
| skip_itc       | false                            |
| skip_devcenter | false                            |
+----------------+----------------------------------+

[18:40:22]: [32m[DevCenter] App 'nl.cruyffclassics.cruyffclassics' already exists, nothing to do on the Dev Center[0m
[18:40:25]: [32mCreating new app '"CRUYFF"' on iTunes Connect[0m
[18:40:26]: [33m[33mVariable Dump:[0m[0m
[18:40:26]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios createnewapp", :XCODEBUILD_DERIVED_DATA_PATH=>nil}
[18:40:26]: [31mYou must choose a primary language. You must choose a primary language.[0m

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.12.1                                           |
| Ruby                | 2.3.1                                             |
| Bundler?            | false                                             |
| Git                 | git version 2.9.3 (Apple Git-75)                  |
| Installation Source | /Users/jenkins/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                        |
| Ruby Lib Dir        | /Users/jenkins/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |
| Is contained        | false                                             |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/       |
| Xcode Version       | 8.1                                               |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | 🚫 Update availaible |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | 🚫 Update availaible |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| fastlane            | 1.109.0 | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.56.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| io-console                | 0.4.5        |
</details>

**Comment by hjanuschka** [comment]
please see https://github.com/fastlane/fastlane/tree/master/deliver#available-language-codes available language codes. 
can you try changing "Dutch" to `nl-NL` - maybe that works.

**Comment by drakar4ik** [comment]
Have same problem, but only for 1 app. All other apps creates normally. 
Our command for creating apps in itunes:
export FASTLANE_PASSWORD='%@'; /usr/local/bin/produce run --skip_devcenter --username \"%@\" --app_name \"%@\" --app_identifier '%@' --app_version '%@' --company_name '%@' --sku '%@'

I see only one difference that app with error from other apps: apple user is new and have no apps in itunes yet. Other users already has other apps in itunes. May be I'll found something else.

**biolinh**, do you have other apps in itunes?

**Comment by drakar4ik** [comment]
+----------------+----------------------------------+
|             Summary for produce 1.3.0             |
+----------------+----------------------------------+
| skip_devcenter | true                             |
| username       | ******             |
| app_name       | VHW Visit Verification Form      |
| app_identifier | ****** |
| app_version    | 1.0.0                            |
| company_name   | Vanguard Health and Wellness LLC |
| sku            | VHW_Visit_Verification_Form      |
| language       | English                          |
| skip_itc       | false                            |
+----------------+----------------------------------+

[12:38:47]: Creating new app 'VHW Visit Verification Form' on iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	You must choose a primary language. You must choose a primary language.

**Comment by Desnoo** [comment]
Same error here.
```
spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:221:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	You must choose a primary language. You must choose a primary language.
	from /Users/Tino/.gem/ruby/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:294:in `create_application!'
	from /Users/Tino/.gem/ruby/2.3.0/gems/spaceship-0.37.0/lib/spaceship/tunes/application.rb:80:in `create!'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/itunes_connect.rb:25:in `create_new_app'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/manager.rb:8:in `start_producing'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:35:in `block (2 levels) in run'
	from /Users/Tino/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/Tino/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/Tino/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/Tino/.gem/ruby/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/Tino/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:133:in `run'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/lib/produce/commands_generator.rb:11:in `start'
	from /Users/Tino/.gem/ruby/2.3.0/gems/produce-1.3.0/bin/produce:6:in `<top (required)>'
	from /Users/Tino/.gem/ruby/2.3.0/bin/produce:22:in `load'
	from /Users/Tino/.gem/ruby/2.3.0/bin/produce:22:in `<main>'

```

**Comment by hjanuschka** [comment]
@biolinh @drakar4ik @Desnoo as its hard to reproduce, i tried it with English, Dutch ... and right now we are unable to reproduce it, but i still have a small bet on the PR, can someone of you be so kind to try the PR out?



```bash
git clone https://github.com/hjanuschka/fastlane fastlane-fork
cd fastlane-fork
git checkout primary_language
#
#  please edit fastlane/Fastfile - and create a demo lane (e.g named: produce_test) - adding 
# your produce() code from the failing fastfile.
#
export FASTLANE_LOCAL_DEV=1
bundle install
bundle exec fastlane produce_test --capture_output
unset FASTLANE_LOCAL_DEV
```

this should use the local forked version including the PR - later on please share the generated output (you'll be asked to auto-copy-paste it)

**Comment by Desnoo** [comment]
@hjanuschka I tried it with another bundle ident and other name then it worked.
I can now say that the error happens if the app name is not unique. This was the case at my side.

**Comment by hjanuschka** [comment]
@Desnoo you mean if an app with the same name already exists?

**Comment by 365SplendidSuns** [comment]
Since updating fastlane 2 days ago I'm getting a problem with languages / localisations too. I have set my language as English in produce and have my metadata in deliver for en-US (Same as I always have) but deliver is failing with this error message.

[en-GB]: You must provide an app description for English (U.K.). [en-GB]: You must enter one or more keywords for your app in English (U.K.). You must add at least one screenshot. You must add at least one screenshot. [en-GB]: You must add at least one screenshot. [en-GB]: You must add at least one screenshot. [en-GB]: You must provide a Support URL.

When I go into iTunes Connect I now have English UK set as the primary language and it is expecting metadate / screenshots etc for English UK localization.

**Comment by Desnoo** [comment]
@hjanuschka Yes that is what I meant.

**Comment by biolinh** [comment]
@drakar4ik It only happen with new account which there don't have any app.

**Comment by stockninja** [comment]
I had exactly this same problem -- as a new iTunesConnect developer making first app.

I created a dummy app in iTunes connect, and after that the bug disappeared.

**Comment by gitig** [comment]
I have the same problem. 
+----------------+------------------------------+
|           Summary for produce 1.3.0           |
+----------------+------------------------------+
| username       | xxxxxxxxxxxxxxxxxxxxxxxxx    |
| app_identifier | xxxxxxxxxx                   |
| app_name       | mYNiceGotGame4               |
| language       | English_UK                   |
| app_version    | 1.5                          |
| sku            | xxxxxxxxxx                 |
| skip_itc       | false                        |
| skip_devcenter | false                        |
+----------------+------------------------------+

the language and app_version options does not work.
language in itunesconnect is "Simplified Chinese" not "English_UK".
app_version in itunesconnect is "1.0" not "1.5".

**Comment by asfalcone** [comment]
Has anyone been able to verify the fix from the PR that @hjanuschka put together? https://github.com/fastlane/fastlane/pull/7084 through the process he [describes in this comment?](https://github.com/fastlane/fastlane/issues/7074#issuecomment-261623278) Let me know so we can get a fix merged!

**Comment by igorstimoli** [comment]
Experiencing the same problem since the last update (v1.110.0)

```
+----------------+---------------------------+
|         Summary for produce 1.3.0          |
+----------------+---------------------------+
| app_name       | ******  |
| language       | UK English                |
| app_version    | 1.0                       |
| sku            | ******                  |
| team_name      | ******               |
| username       | ******    |
| app_identifier | ****** |
| skip_itc       | false                     |
| skip_devcenter | false                     |
| team_id        | ******                |
+----------------+---------------------------+

[16:51:36]: [DevCenter] App '******' already exists, nothing to do on the Dev Center
[16:51:37]: Creating new app '******' on iTunes Connect
[16:51:38]: You must choose a primary language. You must choose a primary language.

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | team_id                                                       | 0           |
| 3    | increment_build_number                                        | 1           |
| 💥    | produce                                                       | 6           |
+------+---------------------------------------------------------------+-------------+

[16:51:38]: fastlane finished with errors

```

**Comment by asfalcone** [comment]
@igorstimoli Could you verify the fix from the PR that @hjanuschka put together? https://github.com/fastlane/fastlane/pull/7084 through the process he [describes in this comment?](https://github.com/fastlane/fastlane/issues/7074#issuecomment-261623278). We're just looking for some external confirmation of the fix so we can merge and ship it! 🚀

**Comment by hjanuschka** [comment]
or someone provide an appleid + password (you can reach me by email) - where we can reproduce it. and try the PR

**Comment by adamipc** [comment]
@asfalcone Doesn't work for me, I get a different error: 

### Captured Output

Command Used: `produce_test`
<details><summary>Output/Log</summary>

```

[23:21:02]: Driving the lane 'produce_test' 🚀
[23:21:02]: ---------------------
[23:21:02]: --- Step: produce ---
[23:21:02]: ---------------------

+----------------+-----------------------------------+
|             Summary for produce 1.3.0              |
+----------------+-----------------------------------+
snip some personal details
| skip_itc       | false                             |
| skip_devcenter | false                             |
+----------------+-----------------------------------+

[23:21:05]: [DevCenter] App 'snip' already exists, nothing to do on the Dev Center
[23:21:07]: Creating new app 'snip' on iTunes Connect
[23:21:07]: Variable Dump:
[23:21:07]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"produce_test"}
[23:21:07]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}

+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 💥    | produce | 4           |
+------+---------+-------------+

[23:21:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Unexpected Error
   https://github.com/fastlane/fastlane/issues/3032 [closed] 2 💬
   22 Sep 2016

➡️  Deliver fails with "Unexpected Error" after uploading package to iTunes Connect
   https://github.com/fastlane/fastlane/issues/6455 [closed] 51 💬
   4 weeks ago

➡️  Deliver fails to create a new version in iTunes Connect for a Mac App
   https://github.com/fastlane/fastlane/issues/6152 [open] 10 💬
   12 hours ago

and 8 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22error%22=%3E[%22Unexpected%20Error%22],%20%22info%22=%3Enil%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.2                           |
| Installation Source | /usr/local/rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :produce_test do
    produce(username: "snip", app_identifier: "snip", team_id: "snip", app_name: 'snip', company_name: "snip", language: "English")
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | 🚫 Update availaible |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | 🚫 Update availaible |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| scan                | 0.14.1  | 🚫 Update availaible |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| io-console                | 0.4.6        |
| rake                      | 11.3.0       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| ast                       | 2.3.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.2        |
| bundler                   | 1.13.6       |
| byebug                    | 9.0.6        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| cork                      | 0.2.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| coderay                   | 1.1.1        |
| docile                    | 1.1.5        |
| simplecov-html            | 0.10.0       |
| simplecov                 | 0.12.0       |
| tins                      | 1.12.0       |
| term-ansicolor            | 1.4.0        |
| thor                      | 0.19.1       |
| coveralls                 | 0.8.15       |
| safe_yaml                 | 1.0.4        |
| crack                     | 0.4.3        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.6.2        |
| redcarpet                 | 3.3.4        |
| danger                    | 0.10.1       |
| diff-lcs                  | 1.2.5        |
| dotenv                    | 2.1.1        |
| fakefs                    | 0.8.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types                | 1.25.1       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| method_source             | 0.8.2        |
| parser                    | 2.3.2.0      |
| powerpack                 | 0.1.1        |
| slop                      | 3.6.0        |
| pry                       | 0.10.4       |
| pry-byebug                | 3.4.0        |
| rainbow                   | 2.1.0        |
| rest-client               | 1.6.9        |
| rspec-support             | 3.1.2        |
| rspec-core                | 3.1.7        |
| rspec-expectations        | 3.1.2        |
| rspec-mocks               | 3.1.3        |
| rspec                     | 3.1.0        |
| rspec_junit_formatter     | 0.2.3        |
| ruby-progressbar          | 1.8.1        |
| unicode-display_width     | 1.1.1        |
| rubocop                   | 0.44.1       |
| webmock                   | 1.19.0       |
| yard                      | 0.8.7.6      |
</details>


*generated on:* **2016-11-21**
</details>

**Comment by adamipc** [comment]
I can't tell whether its actually using the local dev version, I did all the commands that @hjanuschka put together but from the environment stuff in that message it doesn't seem to say its using the dev copy, unless it does that silently.

**Comment by hjanuschka** [comment]
@adamipc - hmm strange, can you post the output of the run without the  PR applied append "--verbose" ?

**Comment by adamipc** [comment]
@hjanuschka Here it is with --verbose on master branch:

### Captured Output

Command Used: `produce_test`
<details><summary>Output/Log</summary>

```

DEBUG [2016-11-22 23:32:29.95]: Checking if there are any plugins that should be loaded...
INFO [2016-11-22 23:32:29.98]: Driving the lane 'produce_test' 🚀
INFO [2016-11-22 23:32:29.98]: ---------------------
INFO [2016-11-22 23:32:29.98]: --- Step: produce ---
INFO [2016-11-22 23:32:29.98]: ---------------------
Comparing spaceship version (remote 0.37.0 - local 0.37.0)

+----------------+-----------------------------------+
|             Summary for produce 1.3.0              |
+----------------+-----------------------------------+
snip
| language       | English                           |
| skip_itc       | false                             |
| skip_devcenter | false                             |
+----------------+-----------------------------------+

INFO [2016-11-22 23:32:35.24]: [DevCenter] App 'snip' already exists, nothing to do on the Dev Center
Looking for iTunes Connect Team with ID snip
INFO [2016-11-22 23:32:36.21]: Creating new app 'snip' on iTunes Connect
WARN [2016-11-22 23:32:36.53]: Variable Dump:
INFO [2016-11-22 23:32:36.53]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"produce_test"}
ERROR [2016-11-22 23:32:36.53]: You must choose a primary language. You must choose a primary language.
INFO [2016-11-22 23:32:36.53]: Successfully generated documentation at path '/Users/adam/Documents/dev/fastlane-fork/fastlane/README.md'

+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 💥    | produce | 6           |
+------+---------+-------------+

ERROR [2016-11-22 23:32:36.54]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	You must choose a primary language. You must choose a primary language.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09You%20must%20choose%20a%20primary%20language.%20You%20must%20choose%20a%20primary%20language.+repo:fastlane/fastlane
➡️  Produce: You must choose a primary language. You must choose a primary language.
   https://github.com/fastlane/fastlane/issues/7074 [open] 18 💬
   3 minutes ago



```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.2                           |
| Installation Source | /usr/local/rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :produce_test do
    produce(username: "snip", app_identifier: "snip", team_id: "snip", app_name: 'snip', company_name: "snip", language: "English", verbose: true)
end

```
</details>

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| io-console                | 0.4.6        |
| rake                      | 11.3.0       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| ast                       | 2.3.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.2        |
| bundler                   | 1.13.6       |
| byebug                    | 9.0.6        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.57.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| cork                      | 0.2.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| coderay                   | 1.1.1        |
| docile                    | 1.1.5        |
| simplecov-html            | 0.10.0       |
| simplecov                 | 0.12.0       |
| tins                      | 1.12.0       |
| term-ansicolor            | 1.4.0        |
| thor                      | 0.19.1       |
| coveralls                 | 0.8.15       |
| safe_yaml                 | 1.0.4        |
| crack                     | 0.4.3        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.6.2        |
| redcarpet                 | 3.3.4        |
| danger                    | 0.10.1       |
| diff-lcs                  | 1.2.5        |
| dotenv                    | 2.1.1        |
| fakefs                    | 0.8.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types                | 1.25.1       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| method_source             | 0.8.2        |
| parser                    | 2.3.2.0      |
| powerpack                 | 0.1.1        |
| slop                      | 3.6.0        |
| pry                       | 0.10.4       |
| pry-byebug                | 3.4.0        |
| rainbow                   | 2.1.0        |
| rest-client               | 1.6.9        |
| rspec-support             | 3.1.2        |
| rspec-core                | 3.1.7        |
| rspec-expectations        | 3.1.2        |
| rspec-mocks               | 3.1.3        |
| rspec                     | 3.1.0        |
| rspec_junit_formatter     | 0.2.3        |
| ruby-progressbar          | 1.8.1        |
| unicode-display_width     | 1.1.1        |
| rubocop                   | 0.44.1       |
| webmock                   | 1.19.0       |
| yard                      | 0.8.7.6      |
</details>


*generated on:* **2016-11-22**
</details>

**Comment by hjanuschka** [comment]
thats so strange! can you give the PR a try again - and changing language to `en-US` in the fastfile ?

**Comment by hjanuschka** [comment]
@adamipc big thx for helping and being so patient.

**Comment by adamipc** [comment]
I probably don't need to paste the whole output, it just says: /Users/adam/Documents/dev/fastlane-fork/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Please enter one of available languages: ["Brazilian Portuguese", "Danish", "Dutch", "English", "English_Australian", "English_CA", "English_UK", "Finnish", "French", "French_CA", "German", "Greek", "Indonesian", "Italian", "Japanese", "Korean", "Malay", "Norwegian", "Portuguese", "Russian", "Simplified Chinese", "Spanish", "Spanish_MX", "Swedish", "Thai", "Traditional Chinese", "Turkish", "Vietnamese"] (FastlaneCore::Interface::FastlaneError)

**Comment by adamipc** [comment]
I hacked it to add en-US to the allowed languages and I'm still getting:

```
/Users/adam/Documents/dev/fastlane-fork/spaceship/lib/spaceship/client.rb:413:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Users/adam/Documents/dev/fastlane-fork/spaceship/lib/spaceship/tunes/tunes_client.rb:293:in `create_application!'
```

**Comment by hjanuschka** [comment]
as @tobiasstrebitzer found out - we need to provide both variations, i updated my pull request, can you pull it and give it a another try?

**Comment by adamipc** [comment]
I'm not sure how to call it, if I use language: "English" or leave the option off, I get the same error, if I set to to en-US then I get the original error that "You must choose a primary language."

**Comment by hjanuschka** [comment]
i updated the PR again :( trigger finger was too fast, lets wait until circel ci finishes with green light 👍 

you then should call it with `English`  as it is converted to en-US automatically.

**Comment by hjanuschka** [comment]
@adamipc  build suceeded - can you try it?

**Comment by adamipc** [comment]
pulled, seem to have latest, but still unexpected response

**Comment by hjanuschka** [comment]
you still have the env set?
```bash
export FASTLANE_LOCAL_DEV=1
bundle install
bundle exec fastlane produce_test --capture_output
```

**Comment by adamipc** [comment]
Yep, and output is still the same as here: https://github.com/fastlane/fastlane/issues/7074#issuecomment-262438554

**Comment by hjanuschka** [comment]
@adamipc  that sucks - can you hack in tunes_client.rb:270
and output the `r` like  adding `puts r.inspect`

**Comment by hjanuschka** [comment]
@adamipc ahh found a nice way to trace spaceship calls :)


export VERBOSE=1
and run the bundle exec

**Comment by adamipc** [comment]
OK, so I was getting a 500 error Internal Server Error and it seemed to be because the bundle ID (even though its in Apple Dev) doesn't show up in iTunes connect. Changing it to a different bundle ID got rid of the error and the create application succeeded.

(No clue why my bundle ID doesn't show up in iTunes connect, but also I guess fastlane can't do anything about internal server error from ITC except show the bug search results like it already does)

**Comment by hjanuschka** [comment]
@adamipc so it even works without the PR now ? that's wierd

**Comment by adamipc** [comment]
No, that is with the PR.

**Comment by hjanuschka** [comment]
ok so the PR is a fix? - and you suffer an additional bug in itc.

**Comment by adamipc** [comment]
Yep!

**Comment by hjanuschka** [comment]
@adamipc  many many thx for your help - and findings!

so can any one else on this issue test the PR?  so we can verify it once again, and get this PR merged?

@asfalcone looks like we are near a solution 👏

**Comment by igorstimoli** [comment]
@asfalcone @hjanuschka
I just tested the fix from the PR and it seems to work... 
At least the process passes that step, yet I get an error later

```
+-------------------------------------+----------------------------------+
|                        Summary for sigh 1.11.2                         |
+-------------------------------------+----------------------------------+
| force                               | true                             |
| adhoc                               | false                            |
| development                         | false                            |
| skip_install                        | false                            |
| app_identifier                      | ************ |
| username                            | ************    |
| team_id                             | ************                       |
| team_name                           | ************                       |
| ignore_profiles_with_different_name | false                            |
| cert_id                             | ************                       |
| skip_fetch_profiles                 | false                            |
| skip_certificate_verification       | false                            |
+-------------------------------------+----------------------------------+

[10:30:06]: Starting login with user '************'
[10:30:08]: Successfully logged in
[10:30:08]: Fetching profiles...
[10:30:09]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[10:30:29]: Creating new provisioning profile for '************' with name '************'
[10:30:32]: Downloading provisioning profile...
[10:30:34]: Successfully downloaded provisioning profile...
[10:30:34]: Installing provisioning profile...
************.mobileprovision
[10:30:34]: Setting Provisioning Profile type to 'app-store'
[10:30:36]: Variable Dump:
[10:30:36]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.", :PRODUCE_APPLE_ID=>"************", :CERT_FILE_PATH=>"/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/************.cer", :CERT_CERTIFICATE_ID=>"************", :SIGH_PROFILE_PATH=>"/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/AppStore_com.************.************.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/AppStore_com.************.************.mobileprovision"], :SIGH_UDID=>"3e62eddd-c680-456d-b78b-dc6ad726a652", :SIGH_UUID=>"3e62eddd-c680-456d-b78b-dc6ad726a652", :SIGH_PROFILE_TYPE=>"app-store"}
[10:30:36]: No value found for 'uuid'

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | team_id                                                       | 0           |
| 3    | increment_build_number                                        | 2           |
| 4    | produce                                                       | 120         |
| 5    | cert                                                          | 37          |
| 6    | pem --force                                                   | 9           |
| 7    | sigh                                                          | 27          |
| 💥    | update_project_code_signing                                   | 0           |
+------+---------------------------------------------------------------+-------------+

[10:30:36]: fastlane finished with errors
```

**Comment by hjanuschka** [comment]
@igorstimoli looks good - from `produce` point of view, can you create a seperate issue - as its another problem just add me with @ and i ll post the answer for it  (as i guess i have one);)

**Comment by asfalcone** [comment]
This was a great team effort! Thanks @hjanuschka for the PR and @igorstimoli, @adamipc and @tobiasstrebitzer for all your help! 🎉 You're all awesome!
