### ISSUE TITLE
Will gym's use_legacy_build_api command always be supported?

### ISSUE THREAD

**Issue by Fengson** [fastlane/fastlane#7625]
I am using `use_legacy_build_api` in my gym process.
Without it, my app won't build. I am getting error 70:
```
2016-12-21 15:34:48.853 xcodebuild[5268:15333] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7ff2320f3e10>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.
```

Will this command still be supported in future fastlane releases and can I depend on it in my company's projects?

Thanks!

**Comment by hjanuschka** [comment]
not sure when it will be removed but infact at some point in time apple may stop to accept those binarys - or as of today, if you require watch-app/watch-extension/imessage.... you already forced to not use it.

from the support side its a nightmare, almost all issues i see here, that contain `use_legacy_build_api=true`  are fixed by turning it off.

there are already a few PR's to mark it as deprecated (more prominent)

but lets get back to your issue, can you provide `fastlane env` and/or `fastlane your_lane --capture_output`  of the lane that produces the error - because i think "fixing the error" should be the way to go instead of betting on some legacy stuff.

**Comment by Fengson** [comment]
I have opened my issue already and it can be found here: https://github.com/fastlane/fastlane/issues/7619

After contacting Travis-CI support I was adviced to add `add_keychain` before match / gym which helped as gym wouldn't work before.

However, after more testing I've discovered that it only works when I set my `export_method` to `app-store`. When it is set to `ad-hoc` I get the following error:

```
2016-12-21 15:34:48.853 xcodebuild[5268:15333] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7ff2320f3e10>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.
Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
** EXPORT FAILED **
+shell_session_update
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-2.1.3/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 59: shell_session_update: command not found
[15:34:48]: Exit status: 70
```

I've been looking for a way to solve it and found this comment by @KrauseFx :
https://github.com/fastlane-old/gym/issues/104#issuecomment-142748015

This in fact made Ad Hoc build work and I was able to upload the app to HockeyApp.

Still, I was getting the errors mentioned in here: https://github.com/fastlane/fastlane/issues/7619
namely:
```
There are no local code signing identities found. You can run `security find-identity -v -p codesigning` to get this output. This Stack Overflow thread has more information: http://stackoverflow.com/q/35390072/774. (Check in Keychain Access for an expired WWDR certificate: http://stackoverflow.com/a/35409835/774 has more info.)
```
but inspite of those errors TravisCI was able to finish match/gym/hockey actions.

**Comment by hjanuschka** [comment]
@Fengson can we channel it to one issue?

can you verify that following gems are installed on the machine:

  * CFPropertyList >=2.3.2
  * sqlite3

as found here: https://forums.developer.apple.com/thread/13446

>jlpiedrahita
>Oct 14, 2015 11:42 AM

**Comment by Fengson** [comment]
@hjanuschka Yes, I closed the other issue.
I have added the following lines in my `before_script` in Travis' settings:
```
- gem install CFPropertyList
- gem install sqlite3
```
2 gems were installed properly, but I'm still getting the same result when I don't use `use_legacy_build_api` for Ad Hoc builds. As mentioned before, App Store works fine without it, just Ad Hoc is problematic.

My log at the end:
```
[21:54:47]: ▸ Touching XYZAPP.app.dSYM
[21:54:50]: ▸ Archive Succeeded
[21:54:53]: Generated plist file with the following values:
[21:54:53]: ▸ -----------------------------------------
[21:54:53]: ▸ {
[21:54:53]: ▸   "method": "ad-hoc"
[21:54:53]: ▸ }
[21:54:53]: ▸ -----------------------------------------
[21:54:53]: $ /usr/bin/xcrun /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-2.2.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_config20161221-1936-17vq5tv.plist' -archivePath /Users/travis/Library/Developer/Xcode/Archives/2016-12-21/XYZAPP\ 2016-12-21\ 21.50.01.xcarchive -exportPath '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_output20161221-1936-1dwgjmp' 
RVM detected, forcing to use system ruby
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
usually this is caused by shell initialization files - check them for 'PATH=...' entries,
it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
Now using system ruby.
+xcodebuild -exportArchive -exportOptionsPlist /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_config20161221-1936-17vq5tv.plist -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2016-12-21/XYZAPP 2016-12-21 21.50.01.xcarchive' -exportPath /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/gym_output20161221-1936-1dwgjmp
2016-12-21 21:54:57.325 xcodebuild[5605:15473] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/XYZAPP Test Server_2016-12-21_21-54-57.308.xcdistributionlogs'.
1.2.840.113635.100.1.61
2016-12-21 21:55:05.696 xcodebuild[5605:15473] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7ff2eba1e6f0>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.
Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
** EXPORT FAILED **
+shell_session_update
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/fastlane-2.2.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 59: shell_session_update: command not found
[21:55:05]: Exit status: 70
[21:55:05]:   For a more detailed error log, check the full log at:
[21:55:05]:   /Users/travis/Library/Logs/gym/XYZAPP-XYZAPP Test Server.log
+---------------------------+-----------------------------------------------------+
|                                  Lane Context                                   |
+---------------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                 |
| PLATFORM_NAME             | ios                                                 |
| LANE_NAME                 | ios matchtest                                       |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/travis/Library/Keychains/login.keychain-db" |
| SIGH_PROFILE_TYPE         | ad-hoc                                              |
+---------------------------+-----------------------------------------------------+
[21:55:05]: Error packaging up the application
```

**Comment by hjanuschka** [comment]
i guess travis runs the gem install under RVM - which is not the one that the archiver uses.

can you try
```
 - rvm use system
- gem install CFPropertyList
- gem install sqlite3
- rvm use 2.0.0
```

**Comment by Fengson** [comment]
Thank you for answer @hjanuschka . I hope we're closer to finishing this issue. However now I'm facing permission issues:

When I add gems like you mentioned, my before_script looks like this:
```
"before_script": [
    "gem install fastlane",
    "rvm use system",
    "gem install CFPropertyList",
    "gem install sqlite3",
    "rvm use 2.0.0"
  ],
```
During the installation, however, I get:
```
3.23s$ gem install fastlane
Fetching: fastlane-2.2.0.gem (100%)
Successfully installed fastlane-2.2.0
1 gem installed
before_script.2
0.31s$ rvm use system
Now using system ruby.
1.68s$ gem install CFPropertyList
Fetching: CFPropertyList-2.3.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
The command "gem install CFPropertyList" failed and exited with 1 during .
```

When I tried using `sudo` for those 2 gems, intalling went fine, but I'm still facing the same issue, even though it says `Now using system ruby.` before failing command.
I guess `sudo` is not desired here. Any way to workaround this issue?

Thank you.

**Comment by hjanuschka** [comment]
hmmmm -  that seems to be travis specific.

you can try this:

```
echo "gem: -n/usr/local/bin" >> ~/.gemrc
```

this should install gems into /usr/local/bin - which should be writeable.
let me know if this helps - and well - can you try if it works even without sqlite3 - is there any detailed build output of the native extension? maybe you are missing something like sqlite-dev package

**Comment by KrauseFx** [comment]
> Will this command still be supported in future fastlane releases and can I depend on it in my company's projects?

Short answer: no

We plan on removing this flag sooner or later. I can imagine that Apple might break the old API with one of the next Xcode releases. We'll add more and more warnings to off-board users from using it.

**Comment by Fengson** [comment]
@hjanuschka I have tried installing gem using:
`gem install -n /usr/local/bin CFPropertyList` but I still get permission denied.

Unfortunately, even with `sudo chown -R $(whoami) /Library/Ruby/Gems/2.0.0` and installing `CFPropertyList` alone I still get error 70 while building with `gym`. I guess `sqlite3` is required for me..

I will try using Gemfile, maybe that will change something? I'm getting a little desperate so I'm willing to try anything. As for sqlite3 I'm getting the following output when installing:

```
ERROR:  Error installing sqlite3:
	ERROR: Failed to build gem native extension.
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/
	--with-pthreadlib
	--without-pthreadlib
	--with-sqlite3lib
	--without-sqlite3lib
Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/sqlite3-1.3.12 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/sqlite3-1.3.12/ext/sqlite3/gem_make.out
The command "gem install sqlite3" failed and exited with 1 during .
```

**Comment by hjanuschka** [comment]
i am not sure if gemfile is a solution - as of then you don't use system ruby anymore - and xcodebuild relays on system ruby 👎 

have you tried installing sqlite3 as the log says? (`brew install sqlite3`)
i am desprate on this one, as i think this is something that probably travis has to fix ?!

**Comment by Fengson** [comment]
@hjanuschka Yes, I did. I tried `brew install sqlite` with `--force` and then added `brew link sqlite3 --force` to suppress warnings saying it's installed but not linked. Nothing worked.

I guess I will stick with `use_legacy_build_api` for as long as it's available and worry some more then.

Thank you for your help and assistance.

**Comment by hjanuschka** [comment]
@Fengson sorry to not being able to help you out, maybe looking for other ios CI services?

**Comment by Fengson** [comment]
Unfortunately, the whole company runs on TravisCI, so there isn't much I can do here I'm afraid.
Oh well!
