### ISSUE TITLE
latest_testflight_buildnumber " You have to specify a new version number error"

### ISSUE THREAD

**Issue by ninaa0718** [fastlane/fastlane#9528]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I am getting an error while trying to fetch the latest TestFlight build number, its always asking for you have to specify new version number

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[Login to iTunes Connect (*******@***.com)
[15:45:59]: Login successful
[15:45:59]: You have to specify a new version number]

if I specify the version number as 5.5.0 ,it is returning the incremented build number as 2 but the latest build number for version 5.5.0 is '54'

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.38.0  | 🚫 Update available |

 Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.0       |
| openssl                   | 2.0.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
</details>

**Comment by phillippbertram** [comment]
I think you have to specify the version if you have multiple versions already published. I had the same error message, so I just provided the current version of my app to `latest_testflight_build_number` like the example below:

```ruby
    version = get_version_number
    latestBuildNumber = latest_testflight_build_number(version: version)
    increment_build_number(
      build_number: latestBuildNumber + 1
    )

    gym

    testflight(skip_waiting_for_build_processing: true)
```

**Comment by ninaa0718** [comment]
The latest_testflight_build_number doesn't return the right build number:-Fetching the latest build number for version 
[09:46:56]: Latest upload is build number: 1
if I specify the version number as 5.5.0 ,it is returning the incremented build number as 2 but the latest build number for version 5.5.0 is '54'

**Comment by ninaa0718** [comment]
Also how can I mention workspace instead of project in the increment_build_number step

**Comment by BogdanTymoshenko** [comment]
For some reason latest_testflight_build_number() always returns 1. Looks like it's iTunesConnect bug

**Comment by Spetruk** [comment]
`latest_testflight_build_number` returns 1 too (((

**Comment by NachoSoto** [comment]
This has started happening to me:
```
[15:11:40]: --------------------------------------------
[15:11:40]: --- Step: latest_testflight_build_number ---
[15:11:40]: --------------------------------------------
[15:11:40]: Login to iTunes Connect (email@xxxxxx.com)
[15:11:42]: Login successful
[15:11:55]: You have to specify a new version number
```

This is my script:
```ruby
  build_number = latest_testflight_build_number(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  ) + 1

  increment_build_number({
    xcodeproj: 'ios/project.xcodeproj',
    build_number: build_number
  })
```

**Comment by NachoSoto** [comment]
Okay I answered my own question, this fixed it for me, and it's objectively better:
```ruby
  project = 'ios/project.xcodeproj'

  build_number = latest_testflight_build_number(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      version: get_version_number(xcodeproj: project)
  ) + 1

  increment_build_number({
    xcodeproj: project,
    build_number: build_number
  })
```

**Comment by NachoSoto** [comment]
Actually never mind, that finds the build to be `1`? (This has been working perfectly for months until today)
```
[15:27:08]: --------------------------------
[15:27:08]: --- Step: get_version_number ---
[15:27:08]: --------------------------------
[15:27:08]: $ cd ~/dev/xxx/ios && agvtool what-marketing-version -terse
......
[15:27:09]: --------------------------------------------
[15:27:09]: --- Step: latest_testflight_build_number ---
[15:27:09]: --------------------------------------------
[15:27:09]: Login to iTunes Connect (email@xxxx.com)
[15:27:12]: Login successful
[15:27:12]: Fetching the latest build number for version 1.0 (<-- This is the correct version)
[15:27:26]: Latest upload is build number: 1 (<-- This is wrong!)
[15:27:26]: ------------------------------------
[15:27:26]: --- Step: increment_build_number ---
[15:27:26]: ------------------------------------
Current version of project XXX is:
    1
```

**Comment by KrauseFx** [comment]
I can confirm that this is a bug

**Comment by KrauseFx** [comment]
Hey everyone, I was just about to look into this, and it seems like the issue is resolved now, even when not providing the `version`. Could you test it again, and let me know if it's resolved?

**Comment by NachoSoto** [comment]
Confirmed, it's working again!

**Comment by KrauseFx** [comment]
Awesome 👍

**Comment by austinlouden** [comment]
I'm still seeing this issue, using fastlane 2.56.0.
It looks like everything returns 1, even for versions that don't exist.

This should return 11:
`[15:35:23]: Login successful
[15:35:24]: Fetching the latest build number for version 6.34
[15:35:30]: Latest upload is build number: 1`

This should return an error possibly?
`[15:35:46]: Login successful
[15:35:47]: Fetching the latest build number for version asdasidki
[15:35:52]: Latest upload is build number: 1`

Using the command like so: `current = latest_testflight_build_number(username: "...", app_identifier: "...", version: "6.34")`

**Comment by osorochich** [comment]
Confirm. The issue still happening to me as well using 2.56.0.

**Comment by marceloreis13** [comment]
I'm using the 2.59.0 version and happening with me too.

**Comment by bex23** [comment]
Same issue here. Running macOS 10.13 and version 2.59.0

**Comment by jkunzelman** [comment]
Also having this issue in 2.61 in High Sierra.

**Comment by rodrigdav** [comment]
I am having this issue with version 2.62.1 .

**Comment by ohayon** [comment]
Hey folks! Could you share the output from your command line so we can have some more context? Also, running things with `--verbose` would be helpful! 🚀

**Comment by marceloreis13** [comment]
Hey @ohayon as you ask, follow the output

This is my lane:
```
lane :currentBuild do
      build = latest_testflight_build_number(version: "5.3.1", live: false, app_identifier: "br.com.xxxxxx")
      puts "########"
      puts build
      puts "########"
end
```

And this is the output:
```
INFO [2017-11-01 10:01:40.73]: --------------------------------------------
INFO [2017-11-01 10:01:40.73]: --- Step: latest_testflight_build_number ---
INFO [2017-11-01 10:01:40.73]: --------------------------------------------
INFO [2017-11-01 10:01:40.74]: Login to iTunes Connect (marcelo.reis@xxxx.com.br)
Looking for iTunes Connect Team with ID XXXXXXX
INFO [2017-11-01 10:01:45.52]: Login successful
INFO [2017-11-01 10:01:46.40]: Fetching the latest build number for version 5.3.1
INFO [2017-11-01 10:01:48.18]: Latest upload is build number: 1
INFO [2017-11-01 10:01:48.22]: ########
INFO [2017-11-01 10:01:48.27]: 1
INFO [2017-11-01 10:01:48.32]: ########
INFO [2017-11-01 10:01:48.32]: Successfully generated documentation at path '/Users/marceloreis/Mobile/Xxxxxx/Novissimo/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | xcode_select           | 0           |
| 4    | xcversion              | 1           |
| 5    | latest_testflight_bui  | 7           |
|      | ld_number              |             |
+------+------------------------+-------------+
```

How can you see, the function returns build 1, but my last build from version 5.3.1 is 17, not 1

**Comment by ohayon** [comment]
Hey @marcelofabri - thanks for sending this output its definitely helpful. I ran this lane with my own bundle ID and version number and the build number came back as expected. What is the current state of your app in TestFlight? Mine is in "Prepare For Submission"

**Comment by osorochich** [comment]
@ohayon as for me, when I try to fetch a build number for the version which isn't released - it works as expected. 
The issue reproduces for me only for the versions which are already released to the store, it always returns build number equals to 1 for such versions.

**Comment by ohayon** [comment]
Could this be because `live: false` is a parameter in the call to the `latest_testflight_build_number` action? When I pass `true` to that parameter, it works as expected for my live version.

**Comment by osorochich** [comment]
I didn't set the `live` parameter at all :/
Now when I pass `true`  everything works as expected, thanks @ohayon!

**Comment by ohayon** [comment]
No problem! Glad you're back up and running!

**Comment by marceloreis13** [comment]
Hi @ohayon, the problem is be cause I need fetch the build from my app in development. When I put `true` works like a charm, but when put `false` (that is my case) don't works.
